/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

/**
 *
 * @author VAIO1
 */
public class FrmAplicarAbono extends javax.swing.JDialog {

    /**
     * Creates new form FrmAplicarAbono
     */
    public FrmAplicarAbono(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngreseCantidad = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnAplicar = new javax.swing.JButton();
        txtCantidadFinal = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngreseCantidad.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblIngreseCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblIngreseCantidad.setText("INGRESE CANTIDAD");
        getContentPane().add(lblIngreseCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        btnAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAplicar.setText("Aplicar");
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        txtCantidadFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCantidadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadFinalActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadFinalActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAplicarAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAplicarAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAplicarAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAplicarAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAplicarAbono dialog = new FrmAplicarAbono(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIngreseCantidad;
    private javax.swing.JTextField txtCantidadFinal;
    // End of variables declaration//GEN-END:variables
}
