/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

/**
 *
 * @author VAIO1
 */
public class FrmAhorros extends javax.swing.JFrame {

    /**
     * Creates new form FrmAhorros
     */
    public FrmAhorros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumerodeCuenta = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        lblCantidadDisponible = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        lblDui = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblBanner1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumerodeCuenta.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblNumerodeCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNumerodeCuenta.setText("Numero de Cuenta");
        getContentPane().add(lblNumerodeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, -250, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -280, 1330, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 830, 40, -1));

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad:");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, -1, -1));

        lblCantidadDisponible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantidadDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadDisponible.setText("________________________________");
        lblCantidadDisponible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblCantidadDisponibleKeyTyped(evt);
            }
        });
        getContentPane().add(lblCantidadDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, -1, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setIconTextGap(-3);
        btnHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 830, 40, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(-3);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasMouseExited(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 840, 90, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 830, 1350, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombres...");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        btnAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, -1, -1));

        btnRetirar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRetirar.setText("Retirar");
        getContentPane().add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, -1, -1));

        lblDui.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDui.setForeground(new java.awt.Color(255, 255, 255));
        lblDui.setText("DUI...");
        getContentPane().add(lblDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        lblApellido.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellidos...");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        lblNit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNit.setForeground(new java.awt.Color(255, 255, 255));
        lblNit.setText("NIT...");
        getContentPane().add(lblNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1340, 860));

        lblBanner1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        //        H.showLogin(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        //H.showMenu(this);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseEntered
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverAtras.png")));
    }//GEN-LAST:event_btnAtrasMouseEntered

    private void btnAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseExited
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png")));
    }//GEN-LAST:event_btnAtrasMouseExited

    private void lblCantidadDisponibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblCantidadDisponibleKeyTyped
        
    }//GEN-LAST:event_lblCantidadDisponibleKeyTyped

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAhorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblBanner1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidadDisponible;
    private javax.swing.JLabel lblDui;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JLabel lblNumerodeCuenta;
    // End of variables declaration//GEN-END:variables
}
