/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;
import java.awt.Color;
import java.sql.SQLException;
import pkgClases.Helper;
/**
 *
 * @author Juan Carlos Cuenca
 */
public class frmBeneficiarios extends javax.swing.JFrame {


    /**
     * Creates new form frmRemesas
     */

    public frmBeneficiarios() {
        initComponents();
        H.CreateComboBoxModel(cmbParentesco1, "SELECT nom_parentesco FROM tbl.Parentescos");
        H.CreateComboBoxModel(cmbPorcentaje1, "SELECT porcentaje_porcentaje FROM tbl.PorcentajesdeSeguros");
        H.CreateComboBoxModel(cmbParentesco2, "SELECT nom_parentesco FROM tbl.Parentescos");
        H.CreateComboBoxModel(cmbPorcentaje2, "SELECT porcentaje_porcentaje FROM tbl.PorcentajesdeSeguros");
        H.CreateComboBoxModel(cmbParentesco3, "SELECT nom_parentesco FROM tbl.Parentescos");
        H.CreateComboBoxModel(cmbPorcentaje3, "SELECT porcentaje_porcentaje FROM tbl.PorcentajesdeSeguros");
        H.CreateComboBoxModel(cmbParentesco4, "SELECT nom_parentesco FROM tbl.Parentescos");
        H.CreateComboBoxModel(cmbPorcentaje4, "SELECT porcentaje_porcentaje FROM tbl.PorcentajesdeSeguros");
        txt4 = new Object[]{txtNomBenef4, txtApeBenef4};
        txt3 = new Object[]{txtNomBenef3, txtApeBenef3};
        txt2 = new Object[]{txtNomBenef2, txtApeBenef2};
        txt1 = new Object[]{txtNomBenef1, txtApeBenef1};
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        txtNomBenef1 = new javax.swing.JTextField();
        txtApeBenef1 = new javax.swing.JTextField();
        txtNomBenef2 = new javax.swing.JTextField();
        txtApeBenef2 = new javax.swing.JTextField();
        txtNomBenef3 = new javax.swing.JTextField();
        txtApeBenef3 = new javax.swing.JTextField();
        txtNomBenef4 = new javax.swing.JTextField();
        txtApeBenef4 = new javax.swing.JTextField();
        cmbPorcentaje1 = new javax.swing.JComboBox();
        cmbParentesco1 = new javax.swing.JComboBox();
        cmbParentesco2 = new javax.swing.JComboBox();
        cmbPorcentaje4 = new javax.swing.JComboBox();
        cmbParentesco3 = new javax.swing.JComboBox();
        cmbPorcentaje2 = new javax.swing.JComboBox();
        cmbParentesco4 = new javax.swing.JComboBox();
        cmbPorcentaje3 = new javax.swing.JComboBox();
        btnAtras2 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripBenef = new javax.swing.JTextArea();
        chkCuarto = new javax.swing.JCheckBox();
        chkTercer = new javax.swing.JCheckBox();
        chkSegundo = new javax.swing.JCheckBox();
        chkPrimer = new javax.swing.JCheckBox();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 730, 40, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setIconTextGap(-3);
        btnHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 730, 40, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(-3);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasMouseExited(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1268, 740, 90, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 728, -1, -1));

        txtNomBenef1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNomBenef1.setText("Nombre");
        txtNomBenef1.setEnabled(false);
        txtNomBenef1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomBenef1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomBenef1FocusLost(evt);
            }
        });
        txtNomBenef1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomBenef1KeyTyped(evt);
            }
        });
        getContentPane().add(txtNomBenef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 200, 40));

        txtApeBenef1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtApeBenef1.setText("Apellido");
        txtApeBenef1.setEnabled(false);
        txtApeBenef1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApeBenef1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApeBenef1FocusLost(evt);
            }
        });
        txtApeBenef1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeBenef1KeyTyped(evt);
            }
        });
        getContentPane().add(txtApeBenef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 200, 40));

        txtNomBenef2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNomBenef2.setText("Nombre");
        txtNomBenef2.setEnabled(false);
        txtNomBenef2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomBenef2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomBenef2FocusLost(evt);
            }
        });
        txtNomBenef2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomBenef2KeyTyped(evt);
            }
        });
        getContentPane().add(txtNomBenef2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 200, 40));

        txtApeBenef2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtApeBenef2.setText("Apellido");
        txtApeBenef2.setEnabled(false);
        txtApeBenef2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApeBenef2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApeBenef2FocusLost(evt);
            }
        });
        txtApeBenef2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeBenef2KeyTyped(evt);
            }
        });
        getContentPane().add(txtApeBenef2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 200, 40));

        txtNomBenef3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNomBenef3.setText("Nombre");
        txtNomBenef3.setEnabled(false);
        txtNomBenef3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomBenef3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomBenef3FocusLost(evt);
            }
        });
        txtNomBenef3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomBenef3KeyTyped(evt);
            }
        });
        getContentPane().add(txtNomBenef3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 200, 40));

        txtApeBenef3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtApeBenef3.setText("Apellido");
        txtApeBenef3.setEnabled(false);
        txtApeBenef3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApeBenef3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApeBenef3FocusLost(evt);
            }
        });
        getContentPane().add(txtApeBenef3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 200, 40));

        txtNomBenef4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNomBenef4.setText("Nombre");
        txtNomBenef4.setEnabled(false);
        txtNomBenef4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomBenef4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomBenef4FocusLost(evt);
            }
        });
        txtNomBenef4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomBenef4KeyTyped(evt);
            }
        });
        getContentPane().add(txtNomBenef4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 200, 40));

        txtApeBenef4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtApeBenef4.setText("Apellido");
        txtApeBenef4.setEnabled(false);
        txtApeBenef4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApeBenef4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApeBenef4FocusLost(evt);
            }
        });
        txtApeBenef4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeBenef4KeyTyped(evt);
            }
        });
        getContentPane().add(txtApeBenef4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, 200, 40));

        cmbPorcentaje1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbPorcentaje1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPorcentaje1.setEnabled(false);
        getContentPane().add(cmbPorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 200, 40));

        cmbParentesco1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbParentesco1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbParentesco1.setEnabled(false);
        getContentPane().add(cmbParentesco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 200, 40));

        cmbParentesco2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbParentesco2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbParentesco2.setEnabled(false);
        getContentPane().add(cmbParentesco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 200, 40));

        cmbPorcentaje4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbPorcentaje4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPorcentaje4.setEnabled(false);
        getContentPane().add(cmbPorcentaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 540, 200, 40));

        cmbParentesco3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbParentesco3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbParentesco3.setEnabled(false);
        getContentPane().add(cmbParentesco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 200, 40));

        cmbPorcentaje2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbPorcentaje2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPorcentaje2.setEnabled(false);
        getContentPane().add(cmbPorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 200, 40));

        cmbParentesco4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbParentesco4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbParentesco4.setEnabled(false);
        getContentPane().add(cmbParentesco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 490, 200, 40));

        cmbPorcentaje3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbPorcentaje3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPorcentaje3.setEnabled(false);
        getContentPane().add(cmbPorcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 200, 40));

        btnAtras2.setText("Atras");
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 200, 50));

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 660, 200, 50));

        jScrollPane1.setBackground(new Color(0,0,0,0f));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txtDescripBenef.setBackground(new Color(0,0,0,0f));
        txtDescripBenef.setColumns(20);
        txtDescripBenef.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtDescripBenef.setLineWrap(true);
        txtDescripBenef.setRows(5);
        txtDescripBenef.setText("Los beneficiarios elegidos pasaran a heredar los fondos depositados\nde la cuenta bancaria cuando el dueño de la cuenta fallece. Se puede \nnombar de uno hasta cuatro beneficiarios.\n\n");
        jScrollPane1.setViewportView(txtDescripBenef);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 770, 150));

        chkCuarto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkCuarto.setText("Cuarto beneficiario");
        chkCuarto.setEnabled(false);
        chkCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCuartoActionPerformed(evt);
            }
        });
        getContentPane().add(chkCuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 330, -1, -1));

        chkTercer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkTercer.setText("Tercer beneficiario");
        chkTercer.setEnabled(false);
        chkTercer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTercerActionPerformed(evt);
            }
        });
        getContentPane().add(chkTercer, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        chkSegundo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkSegundo.setText("Segundo beneficiario");
        chkSegundo.setEnabled(false);
        chkSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSegundoActionPerformed(evt);
            }
        });
        getContentPane().add(chkSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        chkPrimer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkPrimer.setText("Primer beneficiario");
        chkPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPrimerActionPerformed(evt);
            }
        });
        getContentPane().add(chkPrimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    String nomben1, apeben1, paren1, porce1, nomben2, apeben2, paren2, porce2, nomben3, apeben3, paren3, porce3, nomben4, apeben4, paren4, porce4;
    Object[] txt1, txt2, txt3, txt4;
    
    public void getStrings(){
        nomben1 = txtNomBenef1.getText();
        apeben1 = txtApeBenef1.getText();
        paren1 = cmbParentesco1.getSelectedItem().toString();
        porce1 = cmbPorcentaje1.getSelectedItem().toString();
        
        nomben2 = txtNomBenef2.getText();
        apeben2 = txtApeBenef2.getText();
        paren2 = cmbParentesco2.getSelectedItem().toString();
        porce2 = cmbPorcentaje2.getSelectedItem().toString();
        
        nomben3 = txtNomBenef3.getText();
        apeben3 = txtApeBenef3.getText();
        paren3 = cmbParentesco3.getSelectedItem().toString();
        porce3 = cmbPorcentaje3.getSelectedItem().toString();
        
        nomben4 = txtNomBenef4.getText();
        apeben4 = txtApeBenef4.getText();
        paren4 = cmbParentesco4.getSelectedItem().toString();
        porce4 = cmbPorcentaje4.getSelectedItem().toString();
        
    }
    
    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed

    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseEntered
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverAtras.png")));
    }//GEN-LAST:event_btnAtrasMouseEntered

    private void btnAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseExited
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png")));
    }//GEN-LAST:event_btnAtrasMouseExited

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        H.show(this, new frmSeguros());
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try{
            getStrings();
            boolean r = false;
            if(chkCuarto.isSelected()){
                if(H.VerificarCampos(txt1) && H.VerificarCampos(txt2) && H.VerificarCampos(txt3) && H.VerificarCampos(txt4)){
                    if((Integer.parseInt(porce1.replace("%", "")) + Integer.parseInt(porce2.replace("%", "")) + Integer.parseInt(porce3.replace("%", "")) + Integer.parseInt(porce4.replace("%", ""))) == 100){
                        if(H.ExecuteCSTM("EXEC pcd.NuevoSeguro4Beneficiarios ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", new String[]{frmSeguros.id_prima, frmSeguros.nom_tipseguro, frmDatosdeTrabajo.id_cuenta, nomben1, apeben1, paren1, porce1, nomben2, apeben2, paren2, porce2, nomben3, apeben3, paren3, porce3, nomben4, apeben4, paren4, porce4})){
                            H.Message("Seguro correctamente agregado.");
                            r = true;
                        }
                    }else{
                        H.Warning("Porcentajes mal distribuidos.");
                    }
                }else{
                    H.Warning("Complete todos los campos.");
                }
            }else if(chkTercer.isSelected()){
                if(H.VerificarCampos(txt1) && H.VerificarCampos(txt2) && H.VerificarCampos(txt3)){
                    if((Integer.parseInt(porce1.replace("%", "")) + Integer.parseInt(porce2.replace("%", "")) + Integer.parseInt(porce3.replace("%", ""))) == 100){
                        if(H.ExecuteCSTM("EXEC pcd.NuevoSeguro3Beneficiarios ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", new String[]{frmSeguros.id_prima, frmSeguros.nom_tipseguro, frmDatosdeTrabajo.id_cuenta, nomben1, apeben1, paren1, porce1, nomben2, apeben2, paren2, porce2, nomben3, apeben3, paren3, porce3})){
                            H.Message("Seguro correctamente agregado.");
                            r = true;
                        }
                    }else{
                        H.Warning("Porcentajes mal distribuidos.");
                    }
                }else{
                    H.Warning("Complete todos los campos.");
                }
            }else if(chkSegundo.isSelected()){
                if(H.VerificarCampos(txt1) && H.VerificarCampos(txt2)){
                    if((Integer.parseInt(porce1.replace("%", "")) + Integer.parseInt(porce2.replace("%", ""))) == 100){
                        if(H.ExecuteCSTM("EXEC pcd.NuevoSeguro2Beneficiarios ?,?,?,?,?,?,?,?,?,?,?", new String[]{frmSeguros.id_prima, frmSeguros.nom_tipseguro, frmDatosdeTrabajo.id_cuenta, nomben1, apeben1, paren1, porce1, nomben2, apeben2, paren2, porce2})){
                            H.Message("Seguro correctamente agregado.");
                            r = true;
                        }
                    }else{
                        H.Warning("Porcentajes mal distribuidos.");
                    }
                }else{
                    H.Warning("Complete todos los campos.");
                }
            }else if(chkPrimer.isSelected()){
                if(H.VerificarCampos(txt1)){
                    if(Integer.parseInt(porce1.replace("%", "")) == 100){
                        if(H.ExecuteCSTM("EXEC pcd.NuevoSeguro1Beneficiario ?,?,?,?,?,?,?", new String[]{frmSeguros.id_prima, frmSeguros.nom_tipseguro, frmDatosdeTrabajo.id_cuenta, nomben1, apeben1, paren1, porce1})){
                            H.Message("Seguro correctamente agregado.");
                            r = true;
                        }
                    }else{
                        H.Warning("Porcentajes mal distribuidos.");
                    }
                }else{
                    H.Warning("Complete todos los campos.");
                }
            }
            if(r){
                H.showWithTransition(this, new frmTipodeCuenta());
            }
        }catch(SQLException ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void chkPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPrimerActionPerformed
        if(chkPrimer.isSelected()){
            txtNomBenef1.setEnabled(true);
            txtApeBenef1.setEnabled(true);
            cmbParentesco1.setEnabled(true);
            cmbPorcentaje1.setEnabled(true);
            chkSegundo.setEnabled(true);
        }else{
            chkSegundo.setEnabled(false);
            txtNomBenef1.setEnabled(false);
            txtApeBenef1.setEnabled(false);
            cmbParentesco1.setEnabled(false);
            cmbPorcentaje1.setEnabled(false);
        }
    }//GEN-LAST:event_chkPrimerActionPerformed

    private void chkSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSegundoActionPerformed
        if(chkSegundo.isSelected()){
            chkTercer.setEnabled(true);
            txtNomBenef2.setEnabled(true);
            txtApeBenef2.setEnabled(true);
            cmbParentesco2.setEnabled(true);
            cmbPorcentaje2.setEnabled(true);
        }else{
            chkTercer.setEnabled(false);
            txtNomBenef2.setEnabled(false);
            txtApeBenef2.setEnabled(false);
            cmbParentesco2.setEnabled(false);
            cmbPorcentaje2.setEnabled(false);
        }
    }//GEN-LAST:event_chkSegundoActionPerformed

    private void chkTercerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTercerActionPerformed
        if(chkTercer.isSelected()){
            chkCuarto.setEnabled(true);
            txtNomBenef3.setEnabled(true);
            txtApeBenef3.setEnabled(true);
            cmbParentesco3.setEnabled(true);
            cmbPorcentaje3.setEnabled(true);
        }else{
            chkCuarto.setEnabled(false);
            txtNomBenef3.setEnabled(false);
            txtApeBenef3.setEnabled(false);
            cmbParentesco3.setEnabled(false);
            cmbPorcentaje3.setEnabled(false);
        }
    }//GEN-LAST:event_chkTercerActionPerformed

    private void chkCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCuartoActionPerformed
        if(chkCuarto.isSelected()){
            txtNomBenef4.setEnabled(true);
            txtApeBenef4.setEnabled(true);
            cmbParentesco4.setEnabled(true);
            cmbPorcentaje4.setEnabled(true);
        }else{
            txtNomBenef4.setEnabled(false);
            txtApeBenef4.setEnabled(false);
            cmbParentesco4.setEnabled(false);
            cmbPorcentaje4.setEnabled(false);
        }
    }//GEN-LAST:event_chkCuartoActionPerformed

    private void txtNomBenef1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef1FocusGained
        H.focusOn(txtNomBenef1);
    }//GEN-LAST:event_txtNomBenef1FocusGained

    private void txtApeBenef1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef1FocusGained
        H.focusOn(txtApeBenef1);
    }//GEN-LAST:event_txtApeBenef1FocusGained

    private void txtNomBenef2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef2FocusGained
        H.focusOn(txtNomBenef2);
    }//GEN-LAST:event_txtNomBenef2FocusGained

    private void txtApeBenef2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef2FocusGained
        H.focusOn(txtApeBenef2);
    }//GEN-LAST:event_txtApeBenef2FocusGained

    private void txtNomBenef3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef3FocusGained
        H.focusOn(txtNomBenef3);
    }//GEN-LAST:event_txtNomBenef3FocusGained

    private void txtApeBenef3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef3FocusGained
        H.focusOn(txtApeBenef3);
    }//GEN-LAST:event_txtApeBenef3FocusGained

    private void txtNomBenef4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef4FocusGained
        H.focusOn(txtNomBenef4);
    }//GEN-LAST:event_txtNomBenef4FocusGained

    private void txtApeBenef4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef4FocusGained
        H.focusOn(txtApeBenef4);
    }//GEN-LAST:event_txtApeBenef4FocusGained

    private void txtNomBenef1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef1FocusLost
        H.focusOff(txtNomBenef1, "Nombre");
    }//GEN-LAST:event_txtNomBenef1FocusLost

    private void txtNomBenef2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef2FocusLost
        H.focusOff(txtNomBenef2, "Nombre");
    }//GEN-LAST:event_txtNomBenef2FocusLost

    private void txtNomBenef3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef3FocusLost
        H.focusOff(txtNomBenef3, "Nombre");
    }//GEN-LAST:event_txtNomBenef3FocusLost

    private void txtNomBenef4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomBenef4FocusLost
        H.focusOff(txtNomBenef4, "Nombre");
    }//GEN-LAST:event_txtNomBenef4FocusLost

    private void txtApeBenef1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef1FocusLost
        H.focusOff(txtApeBenef1, "Apellido");
    }//GEN-LAST:event_txtApeBenef1FocusLost

    private void txtApeBenef2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef2FocusLost
        H.focusOff(txtApeBenef2, "Apellido");
    }//GEN-LAST:event_txtApeBenef2FocusLost

    private void txtApeBenef3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef3FocusLost
        H.focusOff(txtApeBenef3, "Apellido");
    }//GEN-LAST:event_txtApeBenef3FocusLost

    private void txtApeBenef4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeBenef4FocusLost
        H.focusOff(txtApeBenef4, "Apellido");
    }//GEN-LAST:event_txtApeBenef4FocusLost

    private void txtNomBenef1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomBenef1KeyTyped
        H.ValidarLetras(evt);
    }//GEN-LAST:event_txtNomBenef1KeyTyped

    private void txtApeBenef1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeBenef1KeyTyped
       H.ValidarLetras(evt);
    }//GEN-LAST:event_txtApeBenef1KeyTyped

    private void txtNomBenef2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomBenef2KeyTyped
        H.ValidarLetras(evt);
    }//GEN-LAST:event_txtNomBenef2KeyTyped

    private void txtApeBenef2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeBenef2KeyTyped
       H.ValidarLetras(evt);
    }//GEN-LAST:event_txtApeBenef2KeyTyped

    private void txtNomBenef3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomBenef3KeyTyped
       H.ValidarLetras(evt);
    }//GEN-LAST:event_txtNomBenef3KeyTyped

    private void txtNomBenef4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomBenef4KeyTyped
        H.ValidarLetras(evt);
    }//GEN-LAST:event_txtNomBenef4KeyTyped

    private void txtApeBenef4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeBenef4KeyTyped
        H.ValidarLetras(evt);
    }//GEN-LAST:event_txtApeBenef4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBeneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBeneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBeneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBeneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBeneficiarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox chkCuarto;
    private javax.swing.JCheckBox chkPrimer;
    private javax.swing.JCheckBox chkSegundo;
    private javax.swing.JCheckBox chkTercer;
    private javax.swing.JComboBox cmbParentesco1;
    private javax.swing.JComboBox cmbParentesco2;
    private javax.swing.JComboBox cmbParentesco3;
    private javax.swing.JComboBox cmbParentesco4;
    private javax.swing.JComboBox cmbPorcentaje1;
    private javax.swing.JComboBox cmbPorcentaje2;
    private javax.swing.JComboBox cmbPorcentaje3;
    private javax.swing.JComboBox cmbPorcentaje4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JTextField txtApeBenef1;
    private javax.swing.JTextField txtApeBenef2;
    private javax.swing.JTextField txtApeBenef3;
    private javax.swing.JTextField txtApeBenef4;
    private javax.swing.JTextArea txtDescripBenef;
    private javax.swing.JTextField txtNomBenef1;
    private javax.swing.JTextField txtNomBenef2;
    private javax.swing.JTextField txtNomBenef3;
    private javax.swing.JTextField txtNomBenef4;
    // End of variables declaration//GEN-END:variables
}
