/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmCambiarContraseña extends javax.swing.JDialog {

    /**
     * Creates new form frmCambiarContraseña
     */
    public frmCambiarContraseña(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txts = new Object[]{txtantigua, txtnueva1, txtnueva2};
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtantigua = new javax.swing.JPasswordField();
        txtnueva1 = new javax.swing.JPasswordField();
        txtnueva2 = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese su antigua contraseña:");

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese su nueva contraseña:");

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel3.setText("Confirme su nueva contraseña:");

        txtantigua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtantigua.setForeground(new java.awt.Color(153, 153, 153));
        txtantigua.setText("antiguacontraseña");
        txtantigua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtantiguaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtantiguaFocusLost(evt);
            }
        });

        txtnueva1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnueva1.setForeground(new java.awt.Color(153, 153, 153));
        txtnueva1.setText("nuevacontraseña");
        txtnueva1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnueva1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnueva1FocusLost(evt);
            }
        });

        txtnueva2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnueva2.setForeground(new java.awt.Color(153, 153, 153));
        txtnueva2.setText("nuevacontraseña");
        txtnueva2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnueva2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnueva2FocusLost(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtantigua)
                    .addComponent(txtnueva1)
                    .addComponent(txtnueva2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtantigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnueva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnueva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    Object[] txts;
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try{
        String antigua, antiguaBD, nueva, nueva2;
        antigua = String.valueOf(txtantigua.getPassword());
        nueva = String.valueOf(txtnueva1.getPassword());
        nueva2 = String.valueOf(txtnueva2.getPassword());
        antiguaBD = H.Desencriptar(String.valueOf(H.SearchOne("SELECT contra_usuario FROM tbl.Usuarios WHERE id_usuario = "+H.id_usuario+"")));
        if(H.VerificarCampos(txts)){
            if(nueva.equals(nueva2)){
                if(antiguaBD.equals(antigua)){
                    if(H.ExecuteCSTM("EXEC pcd.ModificarContraseña ?, ?", new String[]{String.valueOf(H.id_usuario), H.Encriptar(nueva)})){
                        H.Message("Contraseña modificada");
                        this.dispose();
                    }else{
                        H.Error("Ocurio un error en el proceso.");
                    }
                }else{
                    H.Warning("La contraseña antigua no coincide.");
                }
            }else{
                H.Warning("Las contraseñas nuevas no coinciden.");
            }
        }else{
            H.Warning("Complete los campos.");
        }
        }catch(SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtantiguaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtantiguaFocusGained
        H.focusOn(txtantigua);
    }//GEN-LAST:event_txtantiguaFocusGained

    private void txtnueva1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnueva1FocusGained
        H.focusOn(txtnueva1);
    }//GEN-LAST:event_txtnueva1FocusGained

    private void txtnueva2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnueva2FocusGained
        H.focusOn(txtnueva2);
    }//GEN-LAST:event_txtnueva2FocusGained

    private void txtantiguaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtantiguaFocusLost
        H.focusOff(txtantigua, "antiguacontraseña");
    }//GEN-LAST:event_txtantiguaFocusLost

    private void txtnueva1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnueva1FocusLost
        H.focusOff(txtnueva1, "nuevacontraseña");
    }//GEN-LAST:event_txtnueva1FocusLost

    private void txtnueva2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnueva2FocusLost
        H.focusOff(txtnueva2, "nuevacontraseña");
    }//GEN-LAST:event_txtnueva2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCambiarContraseña dialog = new frmCambiarContraseña(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtantigua;
    private javax.swing.JPasswordField txtnueva1;
    private javax.swing.JPasswordField txtnueva2;
    // End of variables declaration//GEN-END:variables
}
