/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgFormularios;
import com.itextpdf.text.Font;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pkgClases.Helper;
/**
 *
 * @author GERARDO
 */
public class frmCuentas extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuentas
     */
    public frmCuentas() {
        initComponents();
        rbtNombrecliente.setSelected(true);
        H.fillTable(tblcuenta, "SELECT p.nom_persona AS Nombre, p.ape_persona AS Apellido, c.num_cuenta AS 'Num.Cuenta' FROM tbl.Personas as p, tbl.Cuentas as c WHERE p.id_persona = c.id_persona", new int[]{0,0,1});
        variables = new String[]{id_cuenta, nom, ape, correo, dui, nit , tel, genero, estado, numtarcredito, numtardebito};
        btnPrestamo.setEnabled(false);
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        lbltarjetadebito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcuenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblduicliente = new javax.swing.JLabel();
        lblnomcliente = new javax.swing.JLabel();
        txtnom_cliente = new javax.swing.JTextField();
        lblapellidocliente = new javax.swing.JLabel();
        txttel_cliente = new javax.swing.JFormattedTextField();
        txtDUI = new javax.swing.JFormattedTextField();
        btnClientes1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblduicliente2 = new javax.swing.JLabel();
        rbtNumerodeCuenta = new javax.swing.JRadioButton();
        rbtNombrecliente = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lblapellidocliente1 = new javax.swing.JLabel();
        lblnit = new javax.swing.JLabel();
        txtape_cliente = new javax.swing.JTextField();
        txtNit = new javax.swing.JFormattedTextField();
        lbltelefonocliente1 = new javax.swing.JLabel();
        lblgenero1 = new javax.swing.JLabel();
        lblestado1 = new javax.swing.JLabel();
        lbltarjetadebito1 = new javax.swing.JLabel();
        txtTarjetadeCredito = new javax.swing.JTextField();
        txtTarjetadeDebito = new javax.swing.JTextField();
        btnPrestamo = new javax.swing.JButton();
        txtEstadocivil = new javax.swing.JTextField();
        txtgenero = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 151, -1, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, 40, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setIconTextGap(-3);
        btnHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1268, 740, 90, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 728, -1, -1));

        lbltarjetadebito.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbltarjetadebito.setForeground(new java.awt.Color(255, 255, 255));
        lbltarjetadebito.setText("Tarjeta de Credito:");
        getContentPane().add(lbltarjetadebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 120, 20));

        tblcuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblcuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcuentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcuenta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 450, 540));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 90, -1));

        lblduicliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblduicliente.setForeground(new java.awt.Color(255, 255, 255));
        lblduicliente.setText("Dui del Cliente:");
        getContentPane().add(lblduicliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 110, 20));

        lblnomcliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblnomcliente.setForeground(new java.awt.Color(255, 255, 255));
        lblnomcliente.setText("Nombre Cliente:");
        getContentPane().add(lblnomcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 110, 20));

        txtnom_cliente.setEditable(false);
        txtnom_cliente.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtnom_cliente.setFocusable(false);
        txtnom_cliente.setRequestFocusEnabled(false);
        txtnom_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnom_clienteKeyTyped(evt);
            }
        });
        getContentPane().add(txtnom_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 230, 30));

        lblapellidocliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblapellidocliente.setForeground(new java.awt.Color(255, 255, 255));
        lblapellidocliente.setText("Correo Cliente");
        getContentPane().add(lblapellidocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 120, 20));

        txttel_cliente.setEditable(false);
        try {
            txttel_cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttel_cliente.setText("");
        txttel_cliente.setFocusable(false);
        txttel_cliente.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txttel_cliente.setRequestFocusEnabled(false);
        getContentPane().add(txttel_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 230, 30));

        txtDUI.setEditable(false);
        try {
            txtDUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDUI.setText("");
        txtDUI.setFocusable(false);
        txtDUI.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtDUI.setRequestFocusEnabled(false);
        getContentPane().add(txtDUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 230, 30));

        btnClientes1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnClientes1.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes1.setText("Cliente");
        btnClientes1.setBorderPainted(false);
        btnClientes1.setContentAreaFilled(false);
        btnClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientes1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 120, 30));

        txtBuscar.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 107, 450, -1));

        lblduicliente2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblduicliente2.setText("Nombre Cliente:");
        getContentPane().add(lblduicliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 90, 20));

        rbtNumerodeCuenta.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        rbtNumerodeCuenta.setText("Numero de Cuenta");
        rbtNumerodeCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtNumerodeCuentaMouseClicked(evt);
            }
        });
        rbtNumerodeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNumerodeCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtNumerodeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        rbtNombrecliente.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        rbtNombrecliente.setText("Nombre del cliente ");
        rbtNombrecliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtNombreclienteMouseClicked(evt);
            }
        });
        rbtNombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNombreclienteActionPerformed(evt);
            }
        });
        getContentPane().add(rbtNombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 140, 210, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        lblapellidocliente1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblapellidocliente1.setForeground(new java.awt.Color(255, 255, 255));
        lblapellidocliente1.setText("Apellido Cliente:");
        getContentPane().add(lblapellidocliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 120, 20));

        lblnit.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblnit.setForeground(new java.awt.Color(255, 255, 255));
        lblnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblnit.setText("Nit del cliente:");
        getContentPane().add(lblnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        txtape_cliente.setEditable(false);
        txtape_cliente.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtape_cliente.setFocusable(false);
        txtape_cliente.setRequestFocusEnabled(false);
        txtape_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtape_clienteKeyTyped(evt);
            }
        });
        getContentPane().add(txtape_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 230, 30));

        txtNit.setEditable(false);
        try {
            txtNit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNit.setFocusable(false);
        txtNit.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtNit.setRequestFocusEnabled(false);
        getContentPane().add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 413, 230, 30));

        lbltelefonocliente1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbltelefonocliente1.setForeground(new java.awt.Color(255, 255, 255));
        lbltelefonocliente1.setText("Telefono del Cliente:");
        getContentPane().add(lbltelefonocliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 140, 20));

        lblgenero1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblgenero1.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero1.setText("Genero:");
        getContentPane().add(lblgenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 60, 20));

        lblestado1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblestado1.setForeground(new java.awt.Color(255, 255, 255));
        lblestado1.setText("Estado Civil:");
        getContentPane().add(lblestado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 80, 20));

        lbltarjetadebito1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbltarjetadebito1.setForeground(new java.awt.Color(255, 255, 255));
        lbltarjetadebito1.setText("Tarjeta de Debito:");
        getContentPane().add(lbltarjetadebito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 120, 20));

        txtTarjetadeCredito.setEditable(false);
        txtTarjetadeCredito.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtTarjetadeCredito.setFocusable(false);
        txtTarjetadeCredito.setRequestFocusEnabled(false);
        getContentPane().add(txtTarjetadeCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 230, 30));

        txtTarjetadeDebito.setEditable(false);
        txtTarjetadeDebito.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtTarjetadeDebito.setFocusable(false);
        txtTarjetadeDebito.setRequestFocusEnabled(false);
        getContentPane().add(txtTarjetadeDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 230, 30));

        btnPrestamo.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        btnPrestamo.setText("Prestamo");
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 160, 40));

        txtEstadocivil.setEditable(false);
        txtEstadocivil.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtEstadocivil.setFocusable(false);
        txtEstadocivil.setRequestFocusEnabled(false);
        getContentPane().add(txtEstadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 230, 30));

        txtgenero.setEditable(false);
        txtgenero.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtgenero.setFocusable(false);
        txtgenero.setRequestFocusEnabled(false);
        getContentPane().add(txtgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 230, 30));

        txtcorreo.setEditable(false);
        txtcorreo.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtcorreo.setFocusable(false);
        txtcorreo.setRequestFocusEnabled(false);
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 230, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    ResultSet rs;
    ResultSetMetaData rsmd;
    public static String id_cuenta = "", nom = "", ape = "", correo = "", dui = "", nit = "", tel = "", genero = "", estado = "", numtarcredito = "", numtardebito = "";
    String[] variables;
    
    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        H.cerrarSesion(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        H.Menu(this);   
    }//GEN-LAST:event_btnHomeActionPerformed

    private void tblcuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcuentaMouseClicked
        try{
            id_cuenta = "";
            numtarcredito = "";
            numtardebito = "";
            String num_cuenta = String.valueOf(tblcuenta.getValueAt(tblcuenta.getSelectedRow(), 2));
            rs = H.ExecuteQuery("SELECT nom_persona, ape_persona, correo_persona, dui_datpersona, nit_datpersona, telcasa_datpersona, nom_genero, nom_estadocivil, num_tarjeta, num_cuenta FROM viw.Cliente");
            while(rs.next()){
                if(H.Desencriptar(rs.getString(10)).equals(num_cuenta)){
                    nom = rs.getString(1);
                    ape = rs.getString(2);
                    correo = rs.getString(3);
                    dui = H.Desencriptar(rs.getString(4));
                    nit = H.Desencriptar(rs.getString(5));
                    tel = rs.getString(6);
                    genero = rs.getString(7);
                    estado = rs.getString(8);
                    btnPrestamo.setEnabled(true);
                    if(H.Desencriptar(rs.getString(9)).startsWith("6")){
                        numtarcredito = H.Desencriptar(rs.getString(9));
                    }else if(H.Desencriptar(rs.getString(9)).startsWith("5")){
                        numtardebito = H.Desencriptar(rs.getString(9));
                    }
                }
            }
            String id_persona = String.valueOf(H.SearchOnePSTM("SELECT id_persona FROM tbl.Personas WHERE nom_persona = ? AND ape_persona = ? AND correo_persona = ?", new String[]{nom, ape, correo}));
            id_cuenta = String.valueOf(H.SearchOnePSTM("SELECT id_cuenta FROM tbl.Cuentas WHERE id_persona = ?", new String[]{id_persona}));
            txtnom_cliente.setText(nom);
            txtape_cliente.setText(ape);
            txtcorreo.setText(correo);
            txtDUI.setText(dui);
            txtNit.setText(nit);
            txttel_cliente.setText(tel);
            txtgenero.setText(genero);
            txtEstadocivil.setText(estado);
            if(!"".equals(numtardebito)){
                txtTarjetadeDebito.setText(numtardebito);
            }else{
                txtTarjetadeDebito.setText("No activada.");
            }
            if(!"".equals(numtarcredito)){
                txtTarjetadeCredito.setText(numtarcredito);
            }else{
                txtTarjetadeCredito.setText("No activada");
            }
        } catch (SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_tblcuentaMouseClicked

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void rbtNumerodeCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtNumerodeCuentaMouseClicked

    }//GEN-LAST:event_rbtNumerodeCuentaMouseClicked

    private void rbtNombreclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtNombreclienteMouseClicked

    }//GEN-LAST:event_rbtNombreclienteMouseClicked

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        try{
        if(rbtNombrecliente.isSelected()){
            H.fillTable(tblcuenta, "SELECT p.nom_persona AS Nombre, p.ape_persona AS Apellido, c.num_cuenta AS 'Num.Cuenta' FROM tbl.Personas as p, tbl.Cuentas as c WHERE p.id_persona = c.id_persona AND nom_persona LIKE '%"+txtBuscar.getText()+"%'", new int[]{0,0,1});
        }else if(rbtNumerodeCuenta.isSelected()){
            String num_cuenta = txtBuscar.getText();
            DefaultTableModel defaultmodel = H.CreateTableModel(1);
        defaultmodel.addColumn("defaultcolumn");
        tblcuenta.setModel(defaultmodel);
        H.Cleantbl(tblcuenta);
        DefaultTableModel modelo;
        Object[] fila;       
            rs = H.ExecuteQuery("SELECT p.nom_persona AS Nombre, p.ape_persona AS Apellido, c.num_cuenta AS 'Num.Cuenta' FROM tbl.Personas as p, tbl.Cuentas as c WHERE p.id_persona = c.id_persona");
            rsmd = rs.getMetaData();
            modelo = H.CreateTableModel(rsmd.getColumnCount());
            fila = new Object[rsmd.getColumnCount()];
            for(int i = 0; i < rsmd.getColumnCount(); i++){
                modelo.addColumn(rsmd.getColumnLabel(i+1));
            }
            while(rs.next()){
                if(H.Desencriptar(rs.getString(3)).startsWith(num_cuenta)){
                    fila[0] = rs.getString(1);
                    fila[1] = rs.getString(2);
                    fila[2] = H.Desencriptar(rs.getString(3));
                    modelo.addRow(fila);
                }
            }
            tblcuenta.setModel(modelo);
            tblcuenta.setFont(new java.awt.Font("Ubuntu Light", Font.NORMAL, 14));
            tblcuenta.setForeground(Color.BLACK);
            DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer(){
                java.awt.Font f = new java.awt.Font("Ubuntu", Font.NORMAL, 16);
                
                @Override
                public void setOpaque(boolean isOpaque) {
                    super.setOpaque(true); //To change body of generated methods, choose Tools | Templates.
                }                
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
                    super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    setFont(f);
                    return this;
                }
            };
            headerRenderer.setBackground(new Color(85, 86, 87));
            headerRenderer.setForeground(Color.WHITE);
            for (int i = 0; i < tblcuenta.getModel().getColumnCount(); i++) {
                tblcuenta.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            }
        }
        }catch(SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void rbtNumerodeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNumerodeCuentaActionPerformed
        rbtNombrecliente.setSelected(false);
    }//GEN-LAST:event_rbtNumerodeCuentaActionPerformed

    private void rbtNombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNombreclienteActionPerformed
        rbtNumerodeCuenta.setSelected(false);
    }//GEN-LAST:event_rbtNombreclienteActionPerformed

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        H.show(this, new FrmPrestamos());
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void txtnom_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnom_clienteKeyTyped
        H.ValidarLetras(evt);
    }//GEN-LAST:event_txtnom_clienteKeyTyped

    private void txtape_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtape_clienteKeyTyped
        H.ValidarLetras(evt);
    }//GEN-LAST:event_txtape_clienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JLabel lblapellidocliente;
    private javax.swing.JLabel lblapellidocliente1;
    private javax.swing.JLabel lblduicliente;
    private javax.swing.JLabel lblduicliente2;
    private javax.swing.JLabel lblestado1;
    private javax.swing.JLabel lblgenero1;
    private javax.swing.JLabel lblnit;
    private javax.swing.JLabel lblnomcliente;
    private javax.swing.JLabel lbltarjetadebito;
    private javax.swing.JLabel lbltarjetadebito1;
    private javax.swing.JLabel lbltelefonocliente1;
    private javax.swing.JRadioButton rbtNombrecliente;
    private javax.swing.JRadioButton rbtNumerodeCuenta;
    private javax.swing.JTable tblcuenta;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtDUI;
    private javax.swing.JTextField txtEstadocivil;
    private javax.swing.JFormattedTextField txtNit;
    private javax.swing.JTextField txtTarjetadeCredito;
    private javax.swing.JTextField txtTarjetadeDebito;
    private javax.swing.JTextField txtape_cliente;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtnom_cliente;
    private javax.swing.JFormattedTextField txttel_cliente;
    // End of variables declaration//GEN-END:variables
}
