/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmCargando extends javax.swing.JDialog {

    /**
     * Creates new form frmCargando
     */
    public frmCargando(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        fade.start();
        TestearYComprobarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.setFont(new java.awt.Font("Ubuntu Light", 0, 11)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("Cargando lorem ipsum..");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 410, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCTB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 45, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Control Total Bancario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 100, 290, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyright © | Prototype Development Team");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        fondo.setBackground(new java.awt.Color(40, 40, 40));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/SplashScreen.png"))); // NOI18N
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    
    Timer fade = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 0.0f;
        while(f < 1.0f){
            frmCargando.this.setOpacity(f);
            f += 0.000002f;            
        }
        fade.stop();
     } 
        });
    Timer fadeactual = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 1.0f;
        while(f > 0.01f){
            frmCargando.this.setOpacity(f);
            f -= 0.000002f;            
        }
        fadeactual.stop();
        frmCargando.this.dispose();
        new frmLogin().show();
     } 
        });
    Timer duracion = new Timer (3000, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
        fadeactual.start();
        duracion.stop();
     } 
        });
    public void TestearYComprobarTodo(){
        try{
        txt.setText("Configurando conexion con SQL Server..");
        H.ExecuteQuery("SELECT id_usuario FROM tbl.Usuarios");
        H.ExecuteQueryPSTM("SELECT id_usuario FROM tbl.Usuarios", new String[]{});
        txt.setText("Iniciando cypher, modo: AES 256 bytes..");
        H.AESenc("Prototype");
        txt.setText("Iniciando cypher, modo: RSA 1024 bytes..");
        H.RSAenc("Prototype");
        txt.setText("Terminando configuracion de cypher..");
        H.Encriptar("Prototype");
        txt.setText("Iniciando SCTB: Bancaria..");
        duracion.start();
        }catch(SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex) {
            H.Error(ex.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCargando dialog = new frmCargando(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
