/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmConfirmacion extends javax.swing.JDialog {

    /**
     * Creates new form frmConfirmacion
     */
    public frmConfirmacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        txtTitulo.setText(H.confirm_title);
        txttexto.setText(H.confirm_msj);
        frmConfirmacion.this.setOpacity(0.0f);
        fade2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttexto = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setEditable(false);
        txtTitulo.setBackground(new java.awt.Color(40, 40, 40));
        txtTitulo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 181, 229));
        txtTitulo.setText("¿Lorem ipsum dolor sit amet consectetuer?");
        txtTitulo.setBorder(null);
        txtTitulo.setFocusable(false);
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 340, -1));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txttexto.setEditable(false);
        txttexto.setBackground(new java.awt.Color(40, 40, 40));
        txttexto.setColumns(20);
        txttexto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txttexto.setForeground(new java.awt.Color(255, 255, 255));
        txttexto.setLineWrap(true);
        txttexto.setRows(5);
        txttexto.setText("Lorem ipsum dolor sit amet consectetuer adipiscing elit. aenean commodo ligula eget dolor.");
        txttexto.setWrapStyleWord(true);
        txttexto.setFocusable(false);
        txttexto.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txttexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 370, -1));

        btnOK.setBackground(new Color(0,0,0,0.0f));
        btnOK.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.setBorder(null);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 183, 210, 35));

        btnCancel.setBackground(new Color(0,0,0,0.0f));
        btnCancel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 183, 200, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Confirmation.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    Timer fade;
    
    public void closeThis(){
    fade = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 1.0f;
        while(f > 0.01f){
            frmConfirmacion.this.setOpacity(f);
            f -= 0.00001f;            
        }
        frmConfirmacion.this.dispose();
        fade.stop();        
     } 
        });
    fade.start();
    }
    
    Timer fade2 = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 0.0f;
        while(f < 1.0f){
            frmConfirmacion.this.setOpacity(f);
            f += 0.00001f;            
        }
        fade2.stop();
     } 
        });
        
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        H.confirm_boolean = true;
        closeThis();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        H.confirm_boolean = false;
        closeThis();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConfirmacion dialog = new frmConfirmacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextArea txttexto;
    // End of variables declaration//GEN-END:variables
}
