/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

/**
 *
 * @author Juan Carlos Cuenca
 */
public class frmdAbono extends javax.swing.JDialog {

    /**
     * Creates new form frmdAbono
     */
    public frmdAbono(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblnumerodecuenta2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAbono = new javax.swing.JTable();
        lblnumerodecuenta3 = new javax.swing.JLabel();
        txtNumerodeCuenta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        lblAhorro = new javax.swing.JLabel();
        txtAhorro1 = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnAplicar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Center.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 50));

        lblNombre1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Nombre:");
        getContentPane().add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 110, 20));

        lblCantidad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad a Abonar");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 110, 20));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 240, 30));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 240, 30));

        lblApellido.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 110, 20));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 240, 30));

        lblnumerodecuenta2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblnumerodecuenta2.setForeground(new java.awt.Color(255, 255, 255));
        lblnumerodecuenta2.setText("Numero de Cuenta:");
        getContentPane().add(lblnumerodecuenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 110, 20));

        tblAbono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAbono);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 630, 420));

        lblnumerodecuenta3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblnumerodecuenta3.setForeground(new java.awt.Color(255, 255, 255));
        lblnumerodecuenta3.setText("Abonar a:");
        getContentPane().add(lblnumerodecuenta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 110, 20));
        getContentPane().add(txtNumerodeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 240, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 240, -1));

        lblAhorro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblAhorro.setForeground(new java.awt.Color(255, 255, 255));
        lblAhorro.setText("Ahorro:");
        getContentPane().add(lblAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 110, 20));
        getContentPane().add(txtAhorro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 240, 30));

        btnConsultar.setText("Consultar");
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 170, 40));

        btnAplicar.setText("Aplicar");
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 180, 40));

        btnAtras.setText("Atras");
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 590));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmdAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmdAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmdAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmdAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmdAbono dialog = new frmdAbono(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAhorro;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblnumerodecuenta2;
    private javax.swing.JLabel lblnumerodecuenta3;
    private javax.swing.JTable tblAbono;
    private javax.swing.JTextField txtAhorro1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumerodeCuenta;
    // End of variables declaration//GEN-END:variables
}
