/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmDatosdeTrabajo extends javax.swing.JFrame {

    /**
     * Creates new form frmDatosdeTrabajo
     */
    public frmDatosdeTrabajo() {
        initComponents();
        H.CreateComboBoxModel(cmbpuestosdetrabajos, "SELECT nom_cargotrabajo FROM tbl.CargosdeTrabajos");
        txtSalario.setEnabled(false);
        cmbpuestosdetrabajos.setEnabled(false);
                jTextArea1.setBackground(new Color(0,0,0,0.0f));
                H.fillTable(tblEmpresas, "SELECT nom_datempresa AS Nombre, tel_datempresa AS TEL, dir_datempresa AS Direccion FROM tbl.DatosdeEmpresas", new int[]{0,0,0});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpresas = new javax.swing.JTable();
        txtSalario = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombreEmpresa = new javax.swing.JTextField();
        cmbpuestosdetrabajos = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        tblAtras = new javax.swing.JButton();
        btnAplicar = new javax.swing.JButton();
        lblBanner = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 740, 90, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 340, -1));

        txtBuscador.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscador.setText("Buscar empresa por nombre..");
        txtBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusLost(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 460, -1));

        tblEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpresas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 460, 370));

        txtSalario.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        txtSalario.setForeground(new java.awt.Color(153, 153, 153));
        txtSalario.setText("Salario de la persona");
        txtSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSalarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalarioFocusLost(evt);
            }
        });
        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 410, 50));

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccion.setText("Direccion de la empresa");
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 410, 30));

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Telefono de la empresa");
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 410, 30));

        txtNombreEmpresa.setEditable(false);
        txtNombreEmpresa.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtNombreEmpresa.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreEmpresa.setText("Nombre de la empresa");
        txtNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEmpresaKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 410, 30));

        cmbpuestosdetrabajos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmbpuestosdetrabajos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbpuestosdetrabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 410, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("En este formulario primero elija la \nempresa, luego de elegir la empresa se activaran los campos de puesto y salario, si no aparece la empresa, \npuede agregar una con el boton de abajo, cuando haya completado los datos, prosiga..");
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 400, 310));

        btnAgregar.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar una nueva empresa");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, 400, 60));

        tblAtras.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        tblAtras.setText("Atras");
        tblAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(tblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 180, 80));

        btnAplicar.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        btnAplicar.setText("Siguiente");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, 180, 80));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 727, 1380, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -180, 1390, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    public static String salario_dattrabajo, nom_datempresa, nom_cargotrabajo, id_cuenta;
    
    public void getStrings(){
        salario_dattrabajo = txtSalario.getText();
        nom_datempresa = txtNombreEmpresa.getText();
        nom_cargotrabajo = cmbpuestosdetrabajos.getSelectedItem().toString();
    }
    
    public void cleanStrings(){
        try {
            String[] temp =  new String[]{frmPersonas.nom_persona, frmPersonas.ape_persona, frmPersonas.correo_persona, frmDatosdePersona.dui_datpersona, frmDatosdePersona.nit_datpersona, frmDatosdePersona.dir_datpersona, frmDatosdePersona.telcel_datpersona, frmDatosdePersona.telcasa_datpersona, frmDatosdePersona.nom_genero, frmDatosdePersona.nom_estcivil, salario_dattrabajo, nom_datempresa, nom_cargotrabajo};
            for(int i = 0; i < temp.length; i++){
                temp[i] = null;
            }
        } catch (Exception ex) {
            H.Error(ex.toString());
        }
    }
    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        //        H.showLogin(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        try{
            getStrings();
            if(H.VerificarCampos(new Object[]{txtSalario})){
                int salario = Integer.parseInt(salario_dattrabajo);
                if(salario > 0 && salario < 30000){
                    if(H.ExecuteCSTM("EXEC pcd.AgregarCliente ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?", new String[]{frmPersonas.nom_persona, frmPersonas.ape_persona, frmPersonas.correo_persona, String.valueOf(H.id_usuario), H.Encriptar(frmDatosdePersona.dui_datpersona), H.Encriptar(frmDatosdePersona.nit_datpersona), frmDatosdePersona.dir_datpersona, frmDatosdePersona.telcel_datpersona, frmDatosdePersona.telcasa_datpersona, frmDatosdePersona.nom_genero, frmDatosdePersona.nom_estcivil, salario_dattrabajo, nom_datempresa, nom_cargotrabajo})){
                        String id_per = String.valueOf(H.SearchOne("SELECT id_persona FROM tbl.Personas WHERE correo_persona = '"+frmPersonas.correo_persona+"'"));
                        if(H.ExecuteCSTM("EXEC pcd.NuevaCuenta ?, ?, ?, 'Corriente', 'Activa'", new String[]{frmPersonas.correo_persona, H.Encriptar(id_per), H.Encriptar("0000")})){
                            id_cuenta = String.valueOf(H.SearchOne("SELECT id_cuenta FROM tbl.Cuentas WHERE id_persona = "+id_per));
                            H.showWithTransition(this, new frmSeguros());
                        }
                    }
                }else{
                    H.Warning("Salario invalido");
                }
            }else{
                H.Warning("Salario vacio.");
            }
        }catch(Exception ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void tblAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAtrasActionPerformed
        H.show(this, new frmDatosdePersona());
    }//GEN-LAST:event_tblAtrasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        new frmNuevaEmpresa(this, true).show();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        H.fillTable(tblEmpresas, "SELECT nom_datempresa AS Nombre, tel_datempresa AS TEL, dir_datempresa AS Direccion FROM tbl.DatosdeEmpresas WHERE nom_datempresa LIKE '%"+txtBuscador.getText()+"%'", new int[]{0,0,0});
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void tblEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpresasMouseClicked
        H.tblClicked(tblEmpresas, new Object[]{txtNombreEmpresa, txtTelefono, txtDireccion});
        txtSalario.setEnabled(true);
        cmbpuestosdetrabajos.setEnabled(true);
    }//GEN-LAST:event_tblEmpresasMouseClicked

    private void txtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyTyped
        H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtSalarioKeyTyped

    private void txtBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusGained
        H.focusOn(txtBuscador);
    }//GEN-LAST:event_txtBuscadorFocusGained

    private void txtSalarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalarioFocusGained
        H.focusOn(txtSalario);
    }//GEN-LAST:event_txtSalarioFocusGained

    private void txtSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalarioFocusLost
        H.focusOff(txtSalario, "Salario de la persona");
    }//GEN-LAST:event_txtSalarioFocusLost

    private void txtBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusLost
        H.focusOff(txtBuscador, "Buscar empresa por nombre..");
    }//GEN-LAST:event_txtBuscadorFocusLost

    private void txtNombreEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEmpresaKeyTyped
H.ValidarLetras(evt);
    }//GEN-LAST:event_txtNombreEmpresaKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        H.ValidarLetrayNumeros(evt);
    }//GEN-LAST:event_txtDireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatosdeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatosdeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatosdeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatosdeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatosdeTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JComboBox cmbpuestosdetrabajos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JButton tblAtras;
    private javax.swing.JTable tblEmpresas;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
