/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.awt.Color;
import java.sql.SQLException;
import pkgClases.Helper;

/**
 *
 * @author Juan Carlos Cuenca
 */
public class frmDatosdePersona extends javax.swing.JFrame {

    /**
     * Creates new form frmDatosdePersona
     */
    public frmDatosdePersona() {
        initComponents();
        H.CreateComboBoxModel(cmbGenero, "SELECT nom_genero FROM tbl.Generos");
        H.CreateComboBoxModel(cmbEstadocivil, "SELECT nom_estadocivil FROM tbl.EstadosCiviles");
        txts = new Object[]{txtDui, txtNit, txtTelefonocasa, txtTelefonocel, txtDireccion};
        if(dui_datpersona != null){
            txtDui.setText(dui_datpersona);
            txtNit.setText(nit_datpersona);
            txtTelefonocasa.setText(telcasa_datpersona);
            txtTelefonocel.setText(telcel_datpersona);
            txtDireccion.setText(dir_datpersona);  
            txtDui.setForeground(Color.black);
            txtNit.setForeground(Color.black);
            txtTelefonocel.setForeground(Color.black);
            txtTelefonocasa.setForeground(Color.black);
            txtDireccion.setForeground(Color.black);
        }
                jTextArea1.setBackground(new Color(0,0,0,0.0f));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtTelefonocasa = new javax.swing.JFormattedTextField();
        txtDui = new javax.swing.JFormattedTextField();
        txtNit = new javax.swing.JFormattedTextField();
        txtTelefonocel = new javax.swing.JFormattedTextField();
        cmbEstadocivil = new javax.swing.JComboBox();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox();
        btnAtras = new javax.swing.JButton();
        btnAplicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bienvenido al Sistema de Control Total Bancario.\n\nA continuacion complete todos los campos que se le solicitan, completelos con informacion valida de la persona a ingresar,unas vez completos puede proseguir al siguiente paso..");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 680, 310));

        txtTelefonocasa.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtTelefonocasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefonocasa.setText("2222-2222");
        txtTelefonocasa.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        txtTelefonocasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonocasaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonocasaFocusLost(evt);
            }
        });
        txtTelefonocasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonocasaKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefonocasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 480, 50));

        txtDui.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDui.setText("12345678-9");
        txtDui.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        txtDui.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDuiFocusLost(evt);
            }
        });
        getContentPane().add(txtDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 480, 50));

        txtNit.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtNit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNit.setText("1234-567890-123-4");
        txtNit.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        txtNit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNitFocusLost(evt);
            }
        });
        getContentPane().add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 480, 50));

        txtTelefonocel.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtTelefonocel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefonocel.setText("7777-7777");
        txtTelefonocel.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        txtTelefonocel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonocelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonocelFocusLost(evt);
            }
        });
        txtTelefonocel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonocelKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefonocel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 480, 50));

        cmbEstadocivil.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmbEstadocivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEstadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 480, 50));

        txtDireccion.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccion.setText("Direccion");
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 480, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Center.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1360, 40));

        cmbGenero.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 480, 50));

        btnAtras.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 180, 80));

        btnAplicar.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        btnAplicar.setText("Siguiente");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 610, 180, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    public static String dui_datpersona, nit_datpersona, telcel_datpersona, telcasa_datpersona, nom_genero, nom_estcivil, dir_datpersona;
    Object[] txts;
    
    public void getStrings(){
        dui_datpersona = txtDui.getText();
        nit_datpersona = txtNit.getText();
        telcel_datpersona = txtTelefonocel.getText();
        telcasa_datpersona = txtTelefonocasa.getText();
        dir_datpersona = txtDireccion.getText();
        nom_genero = cmbGenero.getSelectedItem().toString();
        nom_estcivil = cmbEstadocivil.getSelectedItem().toString();
    }
    
    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        try{
            getStrings();
            if(H.VerificarCampos(txts)){
                if(H.ValidarDUI(dui_datpersona)){
                    if(H.notExists("SELECT dui_datpersona FROM tbl.DatosdePersonas", dui_datpersona, 1)){
                        if(H.ValidarNIT(nit_datpersona)){
                            if(H.notExists("SELECT nit_datpersona FROM tbl.DatosdePersonas", nit_datpersona, 1)){
                                if(H.ValidarTelefono(telcel_datpersona)){
                                    if(H.ValidarTelefono(telcasa_datpersona)){
                                        H.showWithTransition(this, new frmDatosdeTrabajo());
                                    }else{
                                        H.Warning("Telefono fijo invalido.");
                                    }
                                }else{
                                    H.Warning("Telefono celular invalido.");
                                }
                            }else{
                                H.Warning("Nit existente.");
                            }
                        }else{
                            H.Warning("Nit invalido.");
                        }
                    }else{
                        H.Warning("Dui existente.");
                    }
                }else{
                    H.Warning("Dui invalido.");
                }
            }else{
                H.Warning("Complete todos los campos.");
                        }
        }catch(SQLException ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        H.show(this, new frmPersonas());
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtDuiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuiFocusGained
        H.focusOn(txtDui);
    }//GEN-LAST:event_txtDuiFocusGained

    private void txtNitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitFocusGained
        H.focusOn(txtNit);
    }//GEN-LAST:event_txtNitFocusGained

    private void txtTelefonocelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonocelFocusGained
        H.focusOn(txtTelefonocel);
    }//GEN-LAST:event_txtTelefonocelFocusGained

    private void txtTelefonocasaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonocasaFocusGained
        H.focusOn(txtTelefonocasa);
    }//GEN-LAST:event_txtTelefonocasaFocusGained

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusGained
        H.focusOn(txtDireccion);
    }//GEN-LAST:event_txtDireccionFocusGained

    private void txtDuiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuiFocusLost
        if("        - ".equals(txtDui.getText())){
        txtDui.setText("12345678-9");
        txtDui.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDuiFocusLost

    private void txtNitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitFocusLost
        if("    -      -   - ".equals(txtNit.getText())){
        txtNit.setText("1234-567890-123-4");
        txtNit.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNitFocusLost

    private void txtTelefonocelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonocelFocusLost
        if("    -    ".equals(txtTelefonocel.getText())){
        txtTelefonocel.setText("7777-7777");
        txtTelefonocel.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTelefonocelFocusLost

    private void txtTelefonocasaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonocasaFocusLost
        if("    -    ".equals(txtTelefonocasa.getText())){
            txtTelefonocasa.setText("2222-2222");
            txtTelefonocasa.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTelefonocasaFocusLost

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        H.focusOff(txtDireccion, "Direccion");
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtTelefonocelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonocelKeyTyped
        H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtTelefonocelKeyTyped

    private void txtTelefonocasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonocasaKeyTyped
  H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtTelefonocasaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatosdePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatosdePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatosdePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatosdePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatosdePersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JComboBox cmbEstadocivil;
    private javax.swing.JComboBox cmbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JFormattedTextField txtNit;
    private javax.swing.JFormattedTextField txtTelefonocasa;
    private javax.swing.JFormattedTextField txtTelefonocel;
    // End of variables declaration//GEN-END:variables
}
