/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmGerentes extends javax.swing.JFrame {

    /**
     * Creates new form frmEmpleados
     */
    public frmGerentes() {
        initComponents();
        H.CreateComboBoxModel(cmbSucursal, "SELECT nom_sucursal FROM tbl.Sucursales");
        H.CreateComboBoxModel(cmbGenero, "SELECT nom_genero FROM tbl.Generos");
        H.CreateComboBoxModel(cmbEstadoCivil, "SELECT nom_estadocivil FROM tbl.EstadosCiviles");
        txts = new Object[]{txtNombres, txtApellidos, txtCorreo, txtDui, txtNit, txtDireccion, txtTel_celular, txtTel_casa, txtUsuario, txtContraseña};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        lblEmpleados = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        cmbSucursal = new javax.swing.JComboBox();
        txtDireccion = new javax.swing.JTextField();
        txtNit = new javax.swing.JFormattedTextField();
        txtDui = new javax.swing.JFormattedTextField();
        txtTel_celular = new javax.swing.JFormattedTextField();
        txtTel_casa = new javax.swing.JFormattedTextField();
        cmbGenero = new javax.swing.JComboBox();
        cmbEstadoCivil = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        lblEstadoCivil = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 730, 40, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setIconTextGap(-3);
        btnHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1268, 740, 90, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 728, -1, -1));

        lblEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleados.setText("Gerentes.");
        getContentPane().add(lblEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtNombres.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(153, 153, 153));
        txtNombres.setText("Nombres");
        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 30));

        txtApellidos.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidos.setText("Apellidos");
        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 30));

        txtCorreo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("Correo electronico");
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 30));

        cmbSucursal.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, 30));

        txtDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccion.setText("Direccion");
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 230, 30));

        txtNit.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtNit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNit.setText("1234-567890-123-4");
        txtNit.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNitFocusLost(evt);
            }
        });
        getContentPane().add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 230, 30));

        txtDui.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDui.setText("12345678-9");
        txtDui.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtDui.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDuiFocusLost(evt);
            }
        });
        getContentPane().add(txtDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 230, 30));

        txtTel_celular.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtTel_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel_celular.setText("7777-7777");
        txtTel_celular.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtTel_celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTel_celularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTel_celularFocusLost(evt);
            }
        });
        txtTel_celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTel_celularKeyTyped(evt);
            }
        });
        getContentPane().add(txtTel_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 220, 30));

        txtTel_casa.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtTel_casa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel_casa.setText("2222-2222");
        txtTel_casa.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtTel_casa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTel_casaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTel_casaFocusLost(evt);
            }
        });
        txtTel_casa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTel_casaKeyTyped(evt);
            }
        });
        getContentPane().add(txtTel_casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        cmbGenero.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 220, 30));

        cmbEstadoCivil.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 220, 30));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 680, 150, 40));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 680, 150, 40));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 680, 140, 40));

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 680, 140, 40));

        txtUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Usuario");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 220, 30));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 750, 520));

        lblEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoCivil.setText("Seleccione el estado civil:");
        getContentPane().add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 230, 30));

        lblSucursal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(255, 255, 255));
        lblSucursal.setText("Seleccione la sucursal:");
        getContentPane().add(lblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Seleccione el genero:");
        getContentPane().add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 190, 30));

        txtContraseña.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(153, 153, 153));
        txtContraseña.setText("Contraseña");
        txtContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusLost(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 220, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, -1, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    Object[] txts;
    String[] data;
    String id, nom_emp, ape_emp, correo_emp, nom_sucursal, dui_datpersona, nit_datpersona, dir_datpersona, telcel_datpersona, telcasa_datpersona, nom_genero, nom_estcivil, usu_ger, contra_ger;
    
    public void getStrings(){
        nom_emp = txtNombres.getText();
        ape_emp = txtApellidos.getText();
        correo_emp = txtCorreo.getText();
        nom_sucursal = cmbSucursal.getSelectedItem().toString();
        dui_datpersona = txtDui.getText();
        nit_datpersona = txtNit.getText();
        dir_datpersona = txtDireccion.getText();
        telcel_datpersona = txtTel_celular.getText();
        telcasa_datpersona = txtTel_casa.getText();
        nom_genero = cmbGenero.getSelectedItem().toString();
        nom_estcivil = cmbEstadoCivil.getSelectedItem().toString();
        usu_ger = txtUsuario.getText();
        contra_ger = String.valueOf(txtContraseña.getPassword());
    }
    
    public void Cargartbl(){
        H.fillTable(tblEmpleados, "SELECT p.nom_persona AS Nombre, p.ape_persona AS Apellido, p.correo_persona AS Correo, s.nom_sucursal AS Sucursal, dp.dui_datpersona AS DUI, dp.nit_datpersona AS NIT, dp.dir_datpersona AS Direccion , dp.telcel_datpersona AS CEL, dp.telcasa_datpersona AS CASA, g.nom_genero AS Genero, ec.nom_estadocivil AS 'Estado civil', u.usu_usuario AS Usuario FROM tbl.Personas as p, tbl.Usuarios as u, tbl.TiposdePersonas as tp, tbl.Sucursales as s, tbl.DatosdePersonas as dp, tbl.Generos as g, tbl.EstadosCiviles as ec, tbl.bitSucursales as bs WHERE p.id_tippersona = tp.id_tippersona AND p.id_tippersona = 3 AND p.id_persona = u.id_persona AND p.id_persona = bs.id_persona AND s.id_sucursal = bs.id_sucursal AND p.id_persona = dp.id_persona AND g.id_genero = dp.id_genero AND ec.id_estadocivil = dp.id_estadocivil", new int[]{0,0,0,0,1,1,0,0,0,0,0,1});
    }
    
    public void setFocusOff(){
        H.focusOff(txtNombres, "Nombres");                                       
        H.focusOff(txtApellidos, "Apellidos");                                    
        H.focusOff(txtCorreo, "Correo electronico");  
        txtDui.setForeground(Color.gray);
        txtDui.setText("12345678-9");
        txtNit.setForeground(Color.gray);
        txtNit.setText("1234-567890-123-4");
        H.focusOff(txtDireccion, "Direccion");
        txtTel_celular.setForeground(Color.gray);
        txtTel_celular.setText("7777-7777");
        txtTel_casa.setForeground(Color.gray);
        txtTel_casa.setText("2222-2222");
        H.focusOff(txtUsuario, "Usuario");                                        
        H.focusOff(txtContraseña, "Contraseña");
    }
    
    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        H.cerrarSesion(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        H.Menu(this);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
         Cargartbl();
        H.LimpiarCampos(txts);
        setFocusOff();
        txtContraseña.setEnabled(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            getStrings();
            if(H.VerificarCampos(txts)){
                if(H.ValidarEmail(correo_emp)){
                    if(H.ValidarDUI(dui_datpersona)){
                        if(H.notExists("SELECT dui_datpersona FROM tbl.DatosdePersonas", dui_datpersona, 1)){
                            if(H.ValidarNIT(nit_datpersona)){
                                if(H.notExists("SELECT nit_datpersona FROM tbl.DatosdePersonas", nit_datpersona, 1)){
                                    if(H.ValidarTelefono(telcel_datpersona)){
                                        if(H.ValidarTelefono(telcasa_datpersona)){
                                            if(H.notExists("SELECT id_persona FROM tbl.Personas WHERE correo_persona = ?", correo_emp, 2)){
                                                if(H.notExists("SELECT usu_usuario FROM tbl.Usuarios", usu_ger, 1)){
                                                    if(
                                                            H.ExecuteCSTM(
                                                                    "EXEC pcd.AgregarGerente ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?", 
                                                                    new String[]{
                                                                        nom_emp, 
                                                                        ape_emp, 
                                                                        correo_emp, 
                                                                        nom_sucursal, 
                                                                        String.valueOf(H.id_usuario), 
                                                                        H.Encriptar(dui_datpersona), 
                                                                        H.Encriptar(nit_datpersona), 
                                                                        dir_datpersona, 
                                                                        telcel_datpersona, 
                                                                        telcasa_datpersona, 
                                                                        nom_genero, 
                                                                        nom_estcivil, 
                                                                        H.Encriptar(usu_ger), 
                                                                        H.Encriptar(contra_ger)
                                                                    })){
                                                        H.Message("Gerente agregado.");
                                                        H.LimpiarCampos(txts);
                                                        setFocusOff();
                                                        Cargartbl();
                                                    }
                                                }else{
                                                    H.Warning("Usuario ya existente.");
                                                }
                                            }else{
                                                H.Warning("Persona ya existente.");
                                            }
                                        }else{
                                            H.Warning("Telefono fijo invalido.");
                                        }
                                    }else{
                                        H.Warning("Telefono celular invalido.");
                                    }
                                }else{
                                    H.Warning("Nit ya existente.");
                                }
                            }else{
                                H.Warning("Nit invalido.");
                            }
                        }else{
                            H.Warning("Dui ya existente.");
                        }
                    }else{
                        H.Warning("Dui invalido.");
                    }
                }else{
                    H.Warning("Introduzca un correo valido.");
                }
            }else{
                H.Warning("No deje campos vacios.");
            }
        }catch(SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try{
            if(H.Confirm("¿Realmente desea eliminar este gerente?")){
                getStrings();
                if(H.VerificarCampos(txts)){
                    if(H.ValidarEmail(correo_emp)){
                        if(H.ValidarTelefono(telcel_datpersona)){
                            if(H.ValidarTelefono(telcasa_datpersona)){
                                if(H.ExecuteCSTM(
                                        "EXEC pcd.ModificarGerente ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?", 
                                        new String[]{
                                            id, 
                                            nom_emp, 
                                            ape_emp, 
                                            correo_emp, 
                                            nom_sucursal, 
                                            H.Encriptar(dui_datpersona), 
                                            H.Encriptar(nit_datpersona), 
                                            dir_datpersona, 
                                            telcel_datpersona, 
                                            telcasa_datpersona, 
                                            nom_genero, 
                                            nom_estcivil, 
                                            H.Encriptar(usu_ger)
                                        })){
                                    H.Message("Gerente modificado.");
                                    H.LimpiarCampos(txts);
                                    setFocusOff();
                                    Cargartbl();
                                    txtContraseña.setEnabled(true);
                                }
                            }else{
                                H.Warning("Telefono fijo invalido.");
                            }
                        }else{
                            H.Warning("Telefono celular invalido.");
                        }
                    }else{
                        H.Warning("Introduzca un correo valido.");
                    }
                }else{
                    H.Warning("No deje campos vacios.");
                }
            }else{
               Cargartbl();
               H.LimpiarCampos(txts);
               setFocusOff();
               txtContraseña.setEnabled(true);
           }
        }catch(SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            getStrings();
           if(H.Confirm("¿Realmente desea eliminar este gerente?")){
               if(
                       H.ExecuteCSTM("EXEC pcd.EliminarGerente ?", 
                               new String[]{correo_emp}
                       ))
               {
                   H.Message("Empleado eliminado.");
                   H.LimpiarCampos(txts);
                   setFocusOff();
                   Cargartbl();
                   txtContraseña.setEnabled(true);
               }
           }else{
               Cargartbl();
               H.LimpiarCampos(txts);
               setFocusOff();
               txtContraseña.setEnabled(true);
           }
       }catch(SQLException ex){
           H.Error(ex.toString());
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        try{
        txtNombres.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 0)));
        txtNombres.setForeground(Color.black);
        txtApellidos.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 1)));
        txtApellidos.setForeground(Color.black);
        txtCorreo.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 2)));
        txtCorreo.setForeground(Color.black);
        cmbSucursal.setSelectedItem(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 3));
        txtDui.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 4)));
        txtDui.setForeground(Color.black);
        txtNit.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 5)));
        txtNit.setForeground(Color.black);
        txtDireccion.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 6)));
        txtDireccion.setForeground(Color.black);
        txtTel_celular.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 7)));
        txtTel_celular.setForeground(Color.black);
        txtTel_casa.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 8)));
        txtTel_casa.setForeground(Color.black);
        cmbGenero.setSelectedItem(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 9));
        cmbEstadoCivil.setSelectedItem(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 10));
        txtUsuario.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(), 11)));
        txtUsuario.setForeground(Color.black);
        id = String.valueOf(H.SearchOnePSTM("SELECT id_persona FROM tbl.Personas WHERE correo_persona = ?", new String[]{correo_emp}));
        txtContraseña.setEnabled(false);
        txtContraseña.setForeground(Color.black);
        }catch(SQLException ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void txtNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusGained
        H.focusOn(txtNombres);
    }//GEN-LAST:event_txtNombresFocusGained

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
        H.focusOff(txtNombres, "Nombres");
    }//GEN-LAST:event_txtNombresFocusLost

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        H.focusOff(txtApellidos, "Apellidos");                                    
    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        H.focusOff(txtCorreo, "Correo electronico");  
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        H.focusOff(txtDireccion, "Direccion");
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtTel_celularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTel_celularFocusLost
        if("    -    ".equals(txtTel_celular.getText())){
        txtTel_celular.setText("7777-7777");
        txtTel_celular.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTel_celularFocusLost

    private void txtTel_casaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTel_casaFocusLost
        if("    -    ".equals(txtTel_casa.getText())){
            txtTel_casa.setText("2222-2222");
            txtTel_casa.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTel_casaFocusLost

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        H.focusOn(txtUsuario);
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        H.focusOff(txtUsuario, "Usuario");                                        
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusLost
        H.focusOff(txtContraseña, "Contraseña");
    }//GEN-LAST:event_txtContraseñaFocusLost

    private void txtApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusGained
        H.focusOn(txtApellidos);
    }//GEN-LAST:event_txtApellidosFocusGained

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        H.focusOn(txtCorreo);
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusGained
        H.focusOn(txtDireccion);
    }//GEN-LAST:event_txtDireccionFocusGained

    private void txtTel_celularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTel_celularFocusGained
        H.focusOn(txtTel_celular);
    }//GEN-LAST:event_txtTel_celularFocusGained

    private void txtTel_casaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTel_casaFocusGained
        H.focusOn(txtTel_casa);
    }//GEN-LAST:event_txtTel_casaFocusGained

    private void txtContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusGained
        H.focusOn(txtContraseña);
    }//GEN-LAST:event_txtContraseñaFocusGained

    private void txtNitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitFocusGained
        H.focusOn(txtNit);
    }//GEN-LAST:event_txtNitFocusGained

    private void txtNitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitFocusLost
         if("    -      -   - ".equals(txtNit.getText())){
        txtNit.setText("1234-567890-123-4");
        txtNit.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNitFocusLost

    private void txtDuiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuiFocusGained
        H.focusOn(txtDui);
    }//GEN-LAST:event_txtDuiFocusGained

    private void txtDuiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuiFocusLost
        if("        - ".equals(txtDui.getText())){
        txtDui.setText("12345678-9");
        txtDui.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDuiFocusLost

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
       H.ValidarLetras(evt);
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
      H.ValidarLetras(evt);
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtTel_celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel_celularKeyTyped
       H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtTel_celularKeyTyped

    private void txtTel_casaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel_casaKeyTyped
        H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtTel_casaKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        H.ValidarLetrayNumeros(evt);
    }//GEN-LAST:event_txtDireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmGerentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbEstadoCivil;
    private javax.swing.JComboBox cmbGenero;
    private javax.swing.JComboBox cmbSucursal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JFormattedTextField txtNit;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JFormattedTextField txtTel_casa;
    private javax.swing.JFormattedTextField txtTel_celular;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
