/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import pkgClases.Helper;

/**
 *
 * @author VAIO1
 */
public class FrmMenuSuperAdmins extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuSuperAdmins
     */
    public FrmMenuSuperAdmins() {
        initComponents();
        lblNombredeUsuario.setText(H.nom_usu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerentes = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnSucursales = new javax.swing.JButton();
        btnAdministrarAdministradores = new javax.swing.JButton();
        btnAdministrarEmpleados = new javax.swing.JButton();
        btbCuentas = new javax.swing.JButton();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerentes.setText("Gerentes");
        btnGerentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerentesMouseEntered(evt);
            }
        });
        btnGerentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerentesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, 80));

        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseEntered(evt);
            }
        });
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        btnAgregarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAgregarClienteFocusGained(evt);
            }
        });
        getContentPane().add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 210, 80));

        btnSucursales.setText("Sucursales");
        btnSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSucursalesMouseEntered(evt);
            }
        });
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        btnSucursales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSucursalesFocusGained(evt);
            }
        });
        getContentPane().add(btnSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 210, 80));

        btnAdministrarAdministradores.setText("Administradores");
        btnAdministrarAdministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdministrarAdministradoresMouseEntered(evt);
            }
        });
        btnAdministrarAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarAdministradoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrarAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, 80));

        btnAdministrarEmpleados.setText("Empleados");
        btnAdministrarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdministrarEmpleadosMouseEntered(evt);
            }
        });
        btnAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, 80));

        btbCuentas.setText("Clientes");
        btbCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btbCuentasMouseEntered(evt);
            }
        });
        btbCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCuentasActionPerformed(evt);
            }
        });
        btbCuentas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btbCuentasFocusGained(evt);
            }
        });
        getContentPane().add(btbCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 210, 80));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 740, 90, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1380, 40));

        lblMenu.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Cuentas.png"))); // NOI18N
        lblMenu.setText("Clientes");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 1390, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    
    private void btnAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarEmpleadosActionPerformed
       H.show(this, new frmEmpleados());
    }//GEN-LAST:event_btnAdministrarEmpleadosActionPerformed

    private void btbCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCuentasActionPerformed
        H.show(this, new frmCuentas());
    }//GEN-LAST:event_btbCuentasActionPerformed

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        H.cerrarSesion(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAdministrarAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarAdministradoresActionPerformed
        H.show(this, new frmAdministradores());
    }//GEN-LAST:event_btnAdministrarAdministradoresActionPerformed

    private void btnAdministrarEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministrarEmpleadosMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Empleados.png")));
        lblMenu.setText("Empleados");
    }//GEN-LAST:event_btnAdministrarEmpleadosMouseEntered

    private void btbCuentasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btbCuentasFocusGained
        
    }//GEN-LAST:event_btbCuentasFocusGained

    private void btnAdministrarAdministradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministrarAdministradoresMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Admins.png")));
        lblMenu.setText("Administradores");
    }//GEN-LAST:event_btnAdministrarAdministradoresMouseEntered

    private void btbCuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbCuentasMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Cuentas.png")));
        lblMenu.setText("Clientes");
    }//GEN-LAST:event_btbCuentasMouseEntered

    private void btnSucursalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucursalesMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Sucursales.png")));
        lblMenu.setText("Sucursales");
    }//GEN-LAST:event_btnSucursalesMouseEntered

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        H.show(this, new frmSucursales());
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnSucursalesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSucursalesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSucursalesFocusGained

    private void btnAgregarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseEntered
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Personas.png")));
        lblMenu.setText("Agregar cliente");
    }//GEN-LAST:event_btnAgregarClienteMouseEntered

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        H.show(this, new frmPersonas());
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnAgregarClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAgregarClienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarClienteFocusGained

    private void btnGerentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerentesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerentesMouseEntered

    private void btnGerentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerentesActionPerformed
        H.show(this, new frmGerentes());
    }//GEN-LAST:event_btnGerentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSuperAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSuperAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSuperAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSuperAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuSuperAdmins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCuentas;
    private javax.swing.JButton btnAdministrarAdministradores;
    private javax.swing.JButton btnAdministrarEmpleados;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGerentes;
    private javax.swing.JButton btnSucursales;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNombredeUsuario;
    // End of variables declaration//GEN-END:variables
}
