/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.sql.SQLException;
import pkgClases.Helper;

/**
 *
 * @author VAIO1
 */
public class FrmPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrestamos
     */
    public FrmPrestamos() {
        initComponents();
        lblNombre.setText(frmCuentas.nom);
        lblApellido.setText(frmCuentas.ape);
        lblDui.setText(frmCuentas.dui);
        lblNit.setText(frmCuentas.nit);
        H.CreateComboBoxModel(cmbtip_prestamo, "SELECT nom_tipprestamo FROM tbl.TiposdePrestamos");
        H.CreateComboBoxModel(cmbplazas, "SELECT nom_plazo FROM tbl.Plazos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttipprestamo = new javax.swing.JTextArea();
        txtplazas = new javax.swing.JTextArea();
        blTipodePrestamo1 = new javax.swing.JLabel();
        blTipodePrestamo = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();
        lblDui = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbplazas = new javax.swing.JComboBox();
        cmbtip_prestamo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        txtMontoprestamo = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttipprestamo.setColumns(20);
        txttipprestamo.setLineWrap(true);
        txttipprestamo.setRows(5);
        txttipprestamo.setText("Aqui puede seleccionar los\ntipos de prestamos que\ntenemos disponibles por favor\nseleccione un item. ");
        txttipprestamo.setWrapStyleWord(true);
        getContentPane().add(txttipprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 290, -1));

        txtplazas.setColumns(20);
        txtplazas.setLineWrap(true);
        txtplazas.setRows(5);
        txtplazas.setText("Seleccione la cantidad\nde plazas en la que\ndesea pagar el prestamo\nsolicitido anteriormente.");
        txtplazas.setWrapStyleWord(true);
        getContentPane().add(txtplazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 490, 280, -1));

        blTipodePrestamo1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        blTipodePrestamo1.setForeground(new java.awt.Color(255, 255, 255));
        blTipodePrestamo1.setText("Monto de Prestamo");
        getContentPane().add(blTipodePrestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        blTipodePrestamo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        blTipodePrestamo.setForeground(new java.awt.Color(255, 255, 255));
        blTipodePrestamo.setText("Tipo de Prestamo");
        getContentPane().add(blTipodePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, -1, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombres...");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        btnAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 670, -1, -1));

        lblDui.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDui.setForeground(new java.awt.Color(255, 255, 255));
        lblDui.setText("DUI...");
        getContentPane().add(lblDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        lblApellido.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellidos...");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        lblNit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNit.setForeground(new java.awt.Color(255, 255, 255));
        lblNit.setText("NIT...");
        getContentPane().add(lblNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plazas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, -1));

        cmbplazas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbplazas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbplazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbplazasActionPerformed(evt);
            }
        });
        getContentPane().add(cmbplazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 460, 180, -1));

        cmbtip_prestamo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbtip_prestamo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbtip_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtip_prestamoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbtip_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 190, 180, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, -1, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 732, 40, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setIconTextGap(-3);
        btnHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 732, 40, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(-3);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasMouseExited(evt);
            }
        });
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 732, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 870, 90, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1370, 40));

        txtMontoprestamo.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        txtMontoprestamo.setForeground(new java.awt.Color(153, 153, 153));
        txtMontoprestamo.setText("Monto del prestamo..");
        txtMontoprestamo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoprestamoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoprestamoFocusLost(evt);
            }
        });
        txtMontoprestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoprestamoKeyTyped(evt);
            }
        });
        getContentPane().add(txtMontoprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 310, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    
    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        H.cerrarSesion(this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        H.Menu(this);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseEntered
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverAtras.png")));
    }//GEN-LAST:event_btnAtrasMouseEntered

    private void btnAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseExited
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png")));
    }//GEN-LAST:event_btnAtrasMouseExited

    private void cmbtip_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtip_prestamoActionPerformed
        try{
            txttipprestamo.setText(String.valueOf(H.SearchOnePSTM("SELECT des_tipprestamo FROM tbl.TiposdePrestamos WHERE nom_tipprestamo = ?", new String[]{cmbtip_prestamo.getSelectedItem().toString()})));
        }catch(SQLException ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_cmbtip_prestamoActionPerformed

    private void cmbplazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbplazasActionPerformed
        try{
            txtplazas.setText(String.valueOf(H.SearchOnePSTM("SELECT cuotasmensuales_plazo FROM tbl.Plazos WHERE nom_plazo = ?", new String[]{cmbplazas.getSelectedItem().toString()})));
        }catch(SQLException ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_cmbplazasActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        H.show(this, new frmCuentas());
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtMontoprestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoprestamoKeyTyped
        H.ValidarNumeros(evt);
    }//GEN-LAST:event_txtMontoprestamoKeyTyped

    private void txtMontoprestamoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoprestamoFocusGained
        H.focusOn(txtMontoprestamo);
    }//GEN-LAST:event_txtMontoprestamoFocusGained

    private void txtMontoprestamoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoprestamoFocusLost
        H.focusOff(txtMontoprestamo, "Monto del prestamo..");
    }//GEN-LAST:event_txtMontoprestamoFocusLost

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        try{
            Object[] txts = new Object[]{txtMontoprestamo};
        if(H.Confirm("¿Esta seguro de querer confirmar este prestamo?")){
            if(H.VerificarCampos(txts)){
                if(H.ExecuteCSTM("EXEC pcd.NuevoPrestamo ?, ?, ?, ?, ?", new String[]{txtMontoprestamo.getText(), cmbtip_prestamo.getSelectedItem().toString(), cmbplazas.getSelectedItem().toString(), "En proceso", frmCuentas.id_cuenta})){
                    H.Message("Prestamo agregado al cliente: "+frmCuentas.nom +" "+frmCuentas.ape+".");
                    H.Menu(this);
                }
            }else{
                H.Warning("Complete el monto del prestamo.");
            }
        }else{
        }
        }catch(SQLException ex){
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blTipodePrestamo;
    private javax.swing.JLabel blTipodePrestamo1;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHome;
    private javax.swing.JComboBox cmbplazas;
    private javax.swing.JComboBox cmbtip_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblDui;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JTextField txtMontoprestamo;
    private javax.swing.JTextArea txtplazas;
    private javax.swing.JTextArea txttipprestamo;
    // End of variables declaration//GEN-END:variables
}
