/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgFormularios;
import java.sql.SQLException;
import pkgClases.Helper;
/**
 *
 * @author GERARDO
 */
public class frmSeguros extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuentas
     */
    public frmSeguros() {
        initComponents();
        H.CreateComboBoxModel(cmbPrimas, "SELECT id_prima FROM tbl.Primas");
        H.CreateComboBoxModel(cmbtipo_seguro, "SELECT nom_tipseguro FROM tbl.TiposdeSeguros");
        try {
            txtmontomensual.setText(String.valueOf(H.SearchOnePSTM("SELECT montomensual_prima FROM tbl.Primas WHERE id_prima = ?", new String[]{cmbPrimas.getSelectedItem().toString()})));
            txtmontoasegurado.setText(String.valueOf(H.SearchOnePSTM("SELECT montoasegurado_prima FROM tbl.Primas WHERE id_prima = ?", new String[]{cmbPrimas.getSelectedItem().toString()})));
            txtdescripcion.setText(String.valueOf(H.SearchOnePSTM("SELECT des_tipseguro FROM tbl.TiposdeSeguros WHERE nom_tipseguro = ?", new String[]{cmbtipo_seguro.getSelectedItem().toString()})));
        } catch (SQLException ex) {
            H.Error(ex.toString());
        }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblNombredeUsuario = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        lblNavegador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblmonto_mensual = new javax.swing.JLabel();
        cmbPrimas = new javax.swing.JComboBox();
        lblprimas_disponibles = new javax.swing.JLabel();
        lbldescripcion_tiposeguro = new javax.swing.JLabel();
        txtmontomensual = new javax.swing.JTextField();
        txtmontoasegurado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        lbltipo_seguro = new javax.swing.JLabel();
        cmbtipo_seguro = new javax.swing.JComboBox();
        lblmonto_asegurado = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 151, -1, -1));

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, 200, 60));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIconTextGap(-3);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 730, 40, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setIconTextGap(-3);
        btnHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 730, 40, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(-3);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasMouseExited(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 40, -1));

        lblHora.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00 AM");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1268, 740, 90, -1));

        lblNombredeUsuario.setFont(new java.awt.Font("Gisha", 0, 20)); // NOI18N
        lblNombredeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombredeUsuario.setText("Nombre de Usuario");
        getContentPane().add(lblNombredeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 340, -1));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Top.png"))); // NOI18N
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNavegador.setBackground(new java.awt.Color(255, 255, 255));
        lblNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        lblNavegador.setOpaque(true);
        getContentPane().add(lblNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 728, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seguros.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        lblmonto_mensual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblmonto_mensual.setForeground(new java.awt.Color(255, 255, 255));
        lblmonto_mensual.setText("Monto mensual.");
        getContentPane().add(lblmonto_mensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        cmbPrimas.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        cmbPrimas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPrimas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbPrimasMouseClicked(evt);
            }
        });
        cmbPrimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrimasActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPrimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 268, 250, 50));

        lblprimas_disponibles.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblprimas_disponibles.setForeground(new java.awt.Color(255, 255, 255));
        lblprimas_disponibles.setText("Primas disponibles:");
        getContentPane().add(lblprimas_disponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        lbldescripcion_tiposeguro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbldescripcion_tiposeguro.setForeground(new java.awt.Color(255, 255, 255));
        lbldescripcion_tiposeguro.setText("Descripcion del tipo de seguro:");
        getContentPane().add(lbldescripcion_tiposeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, -1));

        txtmontomensual.setEditable(false);
        txtmontomensual.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        getContentPane().add(txtmontomensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 270, -1));

        txtmontoasegurado.setEditable(false);
        txtmontoasegurado.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        getContentPane().add(txtmontoasegurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 270, -1));

        txtdescripcion.setEditable(false);
        txtdescripcion.setColumns(20);
        txtdescripcion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        txtdescripcion.setLineWrap(true);
        txtdescripcion.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 530, 320));

        lbltipo_seguro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbltipo_seguro.setForeground(new java.awt.Color(255, 255, 255));
        lbltipo_seguro.setText("Tipo de seguro:");
        getContentPane().add(lbltipo_seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        cmbtipo_seguro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        cmbtipo_seguro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbtipo_seguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtipo_seguroMouseClicked(evt);
            }
        });
        cmbtipo_seguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipo_seguroActionPerformed(evt);
            }
        });
        getContentPane().add(cmbtipo_seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 250, 50));

        lblmonto_asegurado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblmonto_asegurado.setForeground(new java.awt.Color(255, 255, 255));
        lblmonto_asegurado.setText("Monto del asegurado.");
        getContentPane().add(lblmonto_asegurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    public static String id_prima, nom_tipseguro;
    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverCerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/CerrarSesion.png")));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverHome.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Home.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseEntered
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/MouseOverAtras.png")));
    }//GEN-LAST:event_btnAtrasMouseEntered

    private void btnAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseExited
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Atras.png")));
    }//GEN-LAST:event_btnAtrasMouseExited

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cmbPrimasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPrimasMouseClicked
        
    }//GEN-LAST:event_cmbPrimasMouseClicked

    private void cmbtipo_seguroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtipo_seguroMouseClicked
        
    }//GEN-LAST:event_cmbtipo_seguroMouseClicked

    private void cmbPrimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrimasActionPerformed
        try {
            txtmontomensual.setText(String.valueOf(H.SearchOnePSTM("SELECT montomensual_prima FROM tbl.Primas WHERE id_prima = ?", new String[]{cmbPrimas.getSelectedItem().toString()})));
            txtmontoasegurado.setText(String.valueOf(H.SearchOnePSTM("SELECT montoasegurado_prima FROM tbl.Primas WHERE id_prima = ?", new String[]{cmbPrimas.getSelectedItem().toString()})));
        } catch (SQLException ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_cmbPrimasActionPerformed

    private void cmbtipo_seguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipo_seguroActionPerformed
        try {
            txtdescripcion.setText(String.valueOf(H.SearchOnePSTM("SELECT des_tipseguro FROM tbl.TiposdeSeguros WHERE nom_tipseguro = ?", new String[]{cmbtipo_seguro.getSelectedItem().toString()})));
        } catch (SQLException ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_cmbtipo_seguroActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        id_prima = cmbPrimas.getSelectedItem().toString();
        nom_tipseguro = cmbtipo_seguro.getSelectedItem().toString();
        H.showWithTransition(this, new frmBeneficiarios());
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeguros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox cmbPrimas;
    private javax.swing.JComboBox cmbtipo_seguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblNombredeUsuario;
    private javax.swing.JLabel lbldescripcion_tiposeguro;
    private javax.swing.JLabel lblmonto_asegurado;
    private javax.swing.JLabel lblmonto_mensual;
    private javax.swing.JLabel lblprimas_disponibles;
    private javax.swing.JLabel lbltipo_seguro;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtmontoasegurado;
    private javax.swing.JTextField txtmontomensual;
    // End of variables declaration//GEN-END:variables
}
