/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmToast extends javax.swing.JDialog {

    /**
     * Creates new form frmToast
     */
    public frmToast(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Centrar();
        texto.setText(H.toast_msj);
        frmToast.this.setOpacity(0.0f);
        fade.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(40, 40, 40));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(40, 40, 40));
        texto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        texto.setText("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
        texto.setBorder(null);
        texto.setFocusable(false);
        texto.setRequestFocusEnabled(false);
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, 240, -1));

        fondo.setBackground(new java.awt.Color(40, 40, 40));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    public static String txt;
    
    public void Centrar(){
        int ancho, alto, posicionX, posicionY;
        ancho = this.getWidth();
        alto = this.getHeight();
        posicionX = 683 - (ancho / 2);
        posicionY = 650;
        this.setLocation(posicionX, posicionY);
    }
    
    Timer fade = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 0.0f;
        while(f < 1.0f){
            frmToast.this.setOpacity(f);
            f += 0.000002f;            
        }
        duracion.start();
        fade.stop();
     } 
        });
    Timer duracion = new Timer (1500, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
        fadeactual.start();
        duracion.stop();
     } 
        });
    Timer fadeactual = new Timer (1, new ActionListener () { 
    @Override
    public void actionPerformed(ActionEvent e) 
    { 
           float f = 1.0f;
        while(f > 0.01f){
            frmToast.this.setOpacity(f);
            f -= 0.000002f;            
        }
        fadeactual.stop();
        frmToast.this.dispose();
     } 
        });
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmToast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmToast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmToast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmToast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmToast dialog = new frmToast(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
