/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgFormularios;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pkgClases.Helper;

/**
 *
 * @author Carlos
 */
public class frmTipodeCuenta extends javax.swing.JFrame {

    /**
     * Creates new form frmTipodeCuenta
     */
    public frmTipodeCuenta() {
        initComponents();
        H.CreateComboBoxModel(cmbTipodeCuenta, "SELECT nom_tiptarjeta FROM tbl.TiposdeTarjetas");
        H.CreateComboBoxModel(cmbClasesCredito, "SELECT nom_clatarjeta FROM tbl.ClasificaciondeTarjetas WHERE id_tiptarjeta = 2");
        H.CreateComboBoxModel(cmbClasesDebito, "SELECT nom_clatarjeta FROM tbl.ClasificaciondeTarjetas WHERE id_tiptarjeta = 1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbClasesCredito = new javax.swing.JComboBox();
        cmbClasesDebito = new javax.swing.JComboBox();
        chkTarjetadeDebito = new javax.swing.JCheckBox();
        chkTarjetadeCredito = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cmbTipodeCuenta = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCredito = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDebito = new javax.swing.JTextArea();
        btnAplicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbClasesCredito.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbClasesCredito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClasesCredito.setEnabled(false);
        cmbClasesCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClasesCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClasesCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 265, 40));

        cmbClasesDebito.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbClasesDebito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClasesDebito.setEnabled(false);
        cmbClasesDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClasesDebitoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClasesDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 265, 40));

        chkTarjetadeDebito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkTarjetadeDebito.setText("Tarjeta de Debito");
        chkTarjetadeDebito.setEnabled(false);
        chkTarjetadeDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjetadeDebitoActionPerformed(evt);
            }
        });
        getContentPane().add(chkTarjetadeDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, -1, -1));

        chkTarjetadeCredito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkTarjetadeCredito.setText("Tarjeta de Credito");
        chkTarjetadeCredito.setEnabled(false);
        chkTarjetadeCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTarjetadeCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(chkTarjetadeCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elija el tipo de cuenta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        cmbTipodeCuenta.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cmbTipodeCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipodeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipodeCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipodeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 265, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Bancaria Center.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Navegation.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1360, 40));

        txtCredito.setEditable(false);
        txtCredito.setColumns(20);
        txtCredito.setLineWrap(true);
        txtCredito.setRows(5);
        jScrollPane1.setViewportView(txtCredito);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 330, -1));

        txtDebito.setEditable(false);
        txtDebito.setColumns(20);
        txtDebito.setLineWrap(true);
        txtDebito.setRows(5);
        jScrollPane2.setViewportView(txtDebito);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 330, -1));

        btnAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAplicar.setText("Siguiente");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 610, 180, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImagenes/Fondo Menu.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Helper H = new Helper();
    
    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        try{
            boolean realizado = false;
        if(cmbTipodeCuenta.getSelectedItem().toString().equals("Debito")){
            String tempnum_tardebito = H.GenerarTarjeta(1), num_tardebito;
            while(H.notExists("SELECT num_tarjeta FROM tbl.Tarjetas", tempnum_tardebito, 1) == false){
                tempnum_tardebito = H.GenerarTarjeta(1);
            }
            num_tardebito = H.Encriptar(tempnum_tardebito);
            if(H.ExecuteCSTM("EXEC pcd.NuevaTarjetadeDebito ?, ?", new String[]{num_tardebito, frmDatosdeTrabajo.id_cuenta})){
                if(chkTarjetadeDebito.isSelected()){
                if(H.ExecuteCSTM("EXEC pcd.ActivarTarjeta ?, ?", new String[]{num_tardebito, cmbClasesDebito.getSelectedItem().toString()})){
                    realizado = true;
                }
                }
            }
        }else{
            String tempnum_tardebito = H.GenerarTarjeta(1), num_tardebito, temp_numtarcredito = H.GenerarTarjeta(2), num_tarcredito;
            while(H.notExists("SELECT num_tarjeta FROM tbl.Tarjetas", tempnum_tardebito, 1) == false){
                tempnum_tardebito = H.GenerarTarjeta(1);
            }
            while(H.notExists("SELECT num_tarjeta FROM tbl.Tarjetas", temp_numtarcredito, 1) == false){
                temp_numtarcredito = H.GenerarTarjeta(2);
            }
            num_tardebito = H.Encriptar(tempnum_tardebito);
            num_tarcredito = H.Encriptar(temp_numtarcredito);
            if(H.ExecuteCSTM("EXEC pcd.NuevaTarjetadeCreditoyDebito ?, ?, ?", new String[]{num_tardebito, num_tarcredito, frmDatosdeTrabajo.id_cuenta})){
                if(chkTarjetadeDebito.isSelected()){
                    if(H.ExecuteCSTM("EXEC pcd.ActivarTarjeta ?, ?", new String[]{num_tardebito, cmbClasesDebito.getSelectedItem().toString()})){
                        realizado = true;
                    }
                }
                if(chkTarjetadeCredito.isSelected()){
                    if(H.ExecuteCSTM("EXEC pcd.ActivarTarjeta ?, ?", new String[]{num_tarcredito, cmbClasesCredito.getSelectedItem().toString()})){
                        realizado = true;
                    }
                }
            }
        }
        if(realizado){
            H.Menu(this);
        }
        }catch(SQLException ex){
            H.Error(ex.toString());
        } catch (Exception ex) {
            Logger.getLogger(frmTipodeCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void cmbTipodeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipodeCuentaActionPerformed
        if(cmbTipodeCuenta.getSelectedItem().toString().equals("Debito")){
            chkTarjetadeDebito.setEnabled(true);
            chkTarjetadeCredito.setEnabled(false);
        }else{
            chkTarjetadeDebito.setEnabled(true);
            chkTarjetadeCredito.setEnabled(true);
        }
    }//GEN-LAST:event_cmbTipodeCuentaActionPerformed

    private void chkTarjetadeCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjetadeCreditoActionPerformed
        if(chkTarjetadeCredito.isSelected()){
            cmbClasesCredito.setEnabled(true);
        }else{
            cmbClasesCredito.setEnabled(false);
            txtCredito.setText(null);
        }
    }//GEN-LAST:event_chkTarjetadeCreditoActionPerformed

    private void chkTarjetadeDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTarjetadeDebitoActionPerformed
        if(chkTarjetadeDebito.isSelected()){
            cmbClasesDebito.setEnabled(true);
        }else{
            cmbClasesDebito.setEnabled(false);
            txtDebito.setText(null);
        }
    }//GEN-LAST:event_chkTarjetadeDebitoActionPerformed

    private void cmbClasesCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClasesCreditoActionPerformed
        try {
            String nom_clatarjeta = cmbClasesCredito.getSelectedItem().toString();
            String res = (String) H.SearchOne("SELECT des_clatarjeta FROM tbl.ClasificaciondeTarjetas WHERE nom_clatarjeta = '"+nom_clatarjeta+"'");
            txtCredito.setText(res);
        } catch (SQLException ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_cmbClasesCreditoActionPerformed

    private void cmbClasesDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClasesDebitoActionPerformed
        try {
            String nom_clatarjeta = cmbClasesDebito.getSelectedItem().toString();
            String res = (String) H.SearchOne("SELECT des_clatarjeta FROM tbl.ClasificaciondeTarjetas WHERE nom_clatarjeta = '"+nom_clatarjeta+"'");
            txtDebito.setText(res);
        } catch (SQLException ex) {
            H.Error(ex.toString());
        }
    }//GEN-LAST:event_cmbClasesDebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipodeCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JCheckBox chkTarjetadeCredito;
    private javax.swing.JCheckBox chkTarjetadeDebito;
    private javax.swing.JComboBox cmbClasesCredito;
    private javax.swing.JComboBox cmbClasesDebito;
    private javax.swing.JComboBox cmbTipodeCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCredito;
    private javax.swing.JTextArea txtDebito;
    // End of variables declaration//GEN-END:variables
}
